// ============================================================
// PATHFORGE AI — CAREER DATABASE (50+ Careers, All Domains)
// ============================================================

import { Career } from './types';

export const CAREER_DATABASE: Career[] = [
  // ─────────────── TECH & AI ───────────────
  {
    id: 'software_engineer',
    name: 'Software Engineer',
    domain: 'tech_ai',
    difficulty: 7,
    stress_level: 6,
    cost_range_inr: [8, 60],
    cost_range_usd: [60, 300],
    roi_score: 9,
    years_to_establish: 4,
    required_skills: ['Mathematics', 'Logical Thinking', 'Problem Solving', 'Programming'],
    required_exams: [
      { name: 'JEE Main', difficulty: 7, attempts_per_year: 2, eligibility: 'Class 12 (PCM)' },
      { name: 'JEE Advanced', difficulty: 9, attempts_per_year: 1, eligibility: 'JEE Main qualifier' },
    ],
    institutions_india: [
      { name: 'IIT Bombay', location: 'Mumbai', rank: 118, type: 'government', annual_cost_inr: 2.5, acceptance_rate: 1 },
      { name: 'IIT Delhi', location: 'Delhi', rank: 150, type: 'government', annual_cost_inr: 2.3, acceptance_rate: 1 },
      { name: 'IIT Madras', location: 'Chennai', rank: 195, type: 'government', annual_cost_inr: 2.4, acceptance_rate: 1 },
      { name: 'NIT Trichy', location: 'Trichy', rank: 800, type: 'government', annual_cost_inr: 1.5, acceptance_rate: 5 },
      { name: 'BITS Pilani', location: 'Pilani', rank: 450, type: 'deemed', annual_cost_inr: 6, acceptance_rate: 3 },
      { name: 'VIT Vellore', location: 'Vellore', rank: 900, type: 'private', annual_cost_inr: 3, acceptance_rate: 15 },
    ],
    institutions_abroad: [
      { name: 'MIT', location: 'Cambridge, USA', rank: 1, type: 'international', annual_cost_usd: 55, acceptance_rate: 4 },
      { name: 'Stanford University', location: 'Stanford, USA', rank: 2, type: 'international', annual_cost_usd: 57, acceptance_rate: 4 },
      { name: 'Carnegie Mellon', location: 'Pittsburgh, USA', rank: 52, type: 'international', annual_cost_usd: 58, acceptance_rate: 11 },
      { name: 'University of Toronto', location: 'Toronto, Canada', rank: 21, type: 'international', annual_cost_usd: 30, acceptance_rate: 43 },
    ],
    paths: {
      safe: {
        label: 'Safe Path — NIT/State University',
        description: 'Secure admission to a reputed NIT or state engineering college through JEE Main.',
        target_exams: ['JEE Main', 'State CET'],
        institutions: [
          { name: 'NIT Trichy', location: 'Trichy', type: 'government', annual_cost_inr: 1.5 },
          { name: 'NIT Warangal', location: 'Warangal', type: 'government', annual_cost_inr: 1.4 },
        ],
        timeline_years: 4,
        cost_inr_lakhs: 10,
        expected_salary_lpa: 8,
        roi_score: 7,
      },
      balanced: {
        label: 'Balanced Path — BITS/IIIT',
        description: 'Target BITS Pilani or top IIITs; strong placement prospects.',
        target_exams: ['JEE Main', 'BITSAT'],
        institutions: [
          { name: 'BITS Pilani', location: 'Pilani', type: 'deemed', annual_cost_inr: 6 },
          { name: 'IIIT Hyderabad', location: 'Hyderabad', type: 'government', annual_cost_inr: 2 },
        ],
        timeline_years: 4,
        cost_inr_lakhs: 30,
        expected_salary_lpa: 18,
        roi_score: 8,
      },
      aggressive: {
        label: 'Aggressive Path — IIT or Abroad',
        description: 'IIT through JEE Advanced or international scholarship path.',
        target_exams: ['JEE Advanced', 'SAT/ACT (for abroad)'],
        institutions: [
          { name: 'IIT Bombay', location: 'Mumbai', type: 'government', annual_cost_inr: 2.5 },
          { name: 'MIT (Scholarship)', location: 'Cambridge, USA', type: 'international', annual_cost_usd: 10 },
        ],
        timeline_years: 4,
        cost_inr_lakhs: 15,
        expected_salary_lpa: 45,
        roi_score: 10,
      },
    },
    alternatives: ['data_scientist', 'product_manager', 'cybersecurity_analyst'],
    sports_compatible: false,
    description: 'Design and build software systems, apps, and platforms.',
    tags: ['coding', 'programming', 'tech', 'software', 'developer', 'coder', 'it'],
  },

  {
    id: 'data_scientist',
    name: 'Data Scientist / AI Engineer',
    domain: 'tech_ai',
    difficulty: 8,
    stress_level: 6,
    cost_range_inr: [8, 70],
    cost_range_usd: [60, 310],
    roi_score: 9,
    years_to_establish: 5,
    required_skills: ['Mathematics', 'Statistics', 'Programming', 'Machine Learning'],
    required_exams: [
      { name: 'JEE Main', difficulty: 7, attempts_per_year: 2, eligibility: 'Class 12 (PCM)' },
      { name: 'JEE Advanced', difficulty: 9, attempts_per_year: 1, eligibility: 'JEE Main qualifier' },
    ],
    institutions_india: [
      { name: 'IIT Bombay (CSE/DS)', location: 'Mumbai', rank: 118, type: 'government', annual_cost_inr: 2.5 },
      { name: 'IISc Bangalore', location: 'Bangalore', rank: 211, type: 'government', annual_cost_inr: 1.5 },
      { name: 'IIIT Hyderabad', location: 'Hyderabad', rank: 500, type: 'government', annual_cost_inr: 2 },
    ],
    institutions_abroad: [
      { name: 'MIT CSAIL', location: 'Cambridge, USA', rank: 1, type: 'international', annual_cost_usd: 55 },
      { name: 'ETH Zurich', location: 'Zurich, Switzerland', rank: 7, type: 'international', annual_cost_usd: 5 },
    ],
    paths: {
      safe: {
        label: 'Safe — B.Tech CSE + Self-learning',
        description: 'Get into any reputed CS program and build an ML portfolio.',
        target_exams: ['JEE Main', 'State CET'],
        institutions: [{ name: 'NIT/ State Uni (CSE)', location: 'Various', type: 'government', annual_cost_inr: 1.5 }],
        timeline_years: 5,
        cost_inr_lakhs: 12,
        expected_salary_lpa: 12,
        roi_score: 7,
      },
      balanced: {
        label: 'Balanced — IIT/IIIT + Research Internship',
        description: 'IIT or IIIT + research internship at ML labs.',
        target_exams: ['JEE Main', 'JEE Advanced'],
        institutions: [{ name: 'IIT/IIIT (CSE/DS)', location: 'Various', type: 'government', annual_cost_inr: 2 }],
        timeline_years: 5,
        cost_inr_lakhs: 15,
        expected_salary_lpa: 28,
        roi_score: 9,
      },
      aggressive: {
        label: 'Aggressive — IISc + MS abroad',
        description: 'IISc BSc Research → top global MS in ML/AI.',
        target_exams: ['KVPY', 'JEE Advanced', 'GRE'],
        institutions: [
          { name: 'IISc Bangalore', location: 'Bangalore', type: 'government', annual_cost_inr: 1.5 },
          { name: 'CMU MSML Program', location: 'Pittsburgh, USA', type: 'international', annual_cost_usd: 55 },
        ],
        timeline_years: 6,
        cost_inr_lakhs: 50,
        expected_salary_lpa: 80,
        roi_score: 10,
      },
    },
    alternatives: ['software_engineer', 'research_scientist', 'product_manager'],
    sports_compatible: false,
    description: 'Build AI models, analyze data, and derive insights from large datasets.',
    tags: ['ai', 'machine learning', 'data', 'analytics', 'artificial intelligence', 'ml', 'deep learning'],
  },

  {
    id: 'cybersecurity_analyst',
    name: 'Cybersecurity Analyst',
    domain: 'tech_ai',
    difficulty: 7,
    stress_level: 7,
    cost_range_inr: [6, 40],
    cost_range_usd: [40, 200],
    roi_score: 8,
    years_to_establish: 4,
    required_skills: ['Networking', 'Programming', 'Problem Solving', 'Ethical Hacking'],
    required_exams: [
      { name: 'JEE Main', difficulty: 7, attempts_per_year: 2, eligibility: 'Class 12 (PCM)' },
    ],
    institutions_india: [
      { name: 'IIT Kanpur (CSE + Security)', location: 'Kanpur', rank: 264, type: 'government', annual_cost_inr: 2.3 },
      { name: 'CDAC', location: 'Multiple', rank: 0, type: 'government', annual_cost_inr: 1 },
    ],
    institutions_abroad: [
      { name: 'Purdue University', location: 'USA', rank: 88, type: 'international', annual_cost_usd: 40 },
    ],
    paths: {
      safe: {
        label: 'Safe — B.Tech + CEH Certification',
        description: 'CS degree + industry certifications (CEH, OSCP).',
        target_exams: ['JEE Main'],
        institutions: [{ name: 'NIT/State Uni', location: 'Various', type: 'government', annual_cost_inr: 1.5 }],
        timeline_years: 4,
        cost_inr_lakhs: 10,
        expected_salary_lpa: 8,
        roi_score: 7,
      },
      balanced: {
        label: 'Balanced — Specialized Security Degree',
        description: 'Specialized cybersecurity degree + bug bounty portfolio.',
        target_exams: ['JEE Main', 'BITSAT'],
        institutions: [{ name: 'BITS/IIIT (Network Security)', location: 'Various', type: 'deemed', annual_cost_inr: 5 }],
        timeline_years: 4,
        cost_inr_lakhs: 25,
        expected_salary_lpa: 15,
        roi_score: 8,
      },
      aggressive: {
        label: 'Aggressive — Government CERT/Intelligence',
        description: 'Target government cybersecurity agencies or elite firms.',
        target_exams: ['JEE Advanced', 'UPSC (Technical)'],
        institutions: [{ name: 'IIT (CSE + Research)', location: 'IITs', type: 'government', annual_cost_inr: 2.5 }],
        timeline_years: 5,
        cost_inr_lakhs: 15,
        expected_salary_lpa: 30,
        roi_score: 8,
      },
    },
    alternatives: ['software_engineer', 'network_engineer', 'data_scientist'],
    sports_compatible: false,
    description: 'Protect digital systems from cyber threats and attacks.',
    tags: ['hacking', 'security', 'cyber', 'ethical hacking', 'networking', 'infosec'],
  },

  // ─────────────── MEDICAL ───────────────
  {
    id: 'mbbs_doctor',
    name: 'Medical Doctor (MBBS)',
    domain: 'medical',
    difficulty: 9,
    stress_level: 9,
    cost_range_inr: [10, 150],
    cost_range_usd: [100, 500],
    roi_score: 7,
    years_to_establish: 8,
    required_skills: ['Biology', 'Chemistry', 'Memorization', 'Empathy', 'Critical Thinking'],
    required_exams: [
      { name: 'NEET-UG', difficulty: 8, attempts_per_year: 1, eligibility: 'Class 12 (PCB)' },
      { name: 'NEET-PG', difficulty: 9, attempts_per_year: 1, eligibility: 'MBBS Complete' },
    ],
    institutions_india: [
      { name: 'AIIMS Delhi', location: 'Delhi', rank: 1, type: 'government', annual_cost_inr: 0.1, acceptance_rate: 0.1 },
      { name: 'Maulana Azad Medical College', location: 'Delhi', rank: 5, type: 'government', annual_cost_inr: 0.2, acceptance_rate: 0.5 },
      { name: 'Armed Forces Medical College', location: 'Pune', rank: 10, type: 'government', annual_cost_inr: 0.1 },
      { name: 'Kasturba Medical College', location: 'Manipal', rank: 15, type: 'deemed', annual_cost_inr: 15 },
    ],
    institutions_abroad: [
      { name: 'Harvard Medical School', location: 'Boston, USA', rank: 1, type: 'international', annual_cost_usd: 65 },
      { name: 'MBBS in Russia (Top Universities)', location: 'Russia', rank: 0, type: 'international', annual_cost_usd: 7 },
      { name: 'MBBS in Ukraine/Philippines', location: 'Multiple', rank: 0, type: 'international', annual_cost_usd: 5 },
    ],
    paths: {
      safe: {
        label: 'Safe — State/Private Medical College',
        description: 'NEET score good enough for state government or private medical college.',
        target_exams: ['NEET-UG'],
        institutions: [{ name: 'State Medical Colleges', location: 'Various', type: 'government', annual_cost_inr: 1 }],
        timeline_years: 8,
        cost_inr_lakhs: 30,
        expected_salary_lpa: 10,
        roi_score: 6,
      },
      balanced: {
        label: 'Balanced — Central/Top State Government',
        description: 'Score 550+ in NEET and target top government colleges.',
        target_exams: ['NEET-UG'],
        institutions: [
          { name: 'Maulana Azad Medical College', location: 'Delhi', type: 'government', annual_cost_inr: 0.2 },
          { name: 'JIPMER Puducherry', location: 'Puducherry', type: 'government', annual_cost_inr: 0.1 },
        ],
        timeline_years: 8,
        cost_inr_lakhs: 10,
        expected_salary_lpa: 15,
        roi_score: 7,
      },
      aggressive: {
        label: 'Aggressive — AIIMS Delhi',
        description: '680+ in NEET, AIIMS Delhi — elite pathway with residency.',
        target_exams: ['NEET-UG (680+)', 'NEET-PG'],
        institutions: [
          { name: 'AIIMS Delhi', location: 'Delhi', type: 'government', annual_cost_inr: 0.1 },
        ],
        timeline_years: 10,
        cost_inr_lakhs: 5,
        expected_salary_lpa: 35,
        roi_score: 9,
      },
    },
    alternatives: ['dentist', 'pharmacist', 'physiotherapist', 'bams_doctor'],
    sports_compatible: false,
    description: 'Become a licensed medical professional diagnosing and treating patients.',
    tags: ['doctor', 'medicine', 'medical', 'physician', 'mbbs', 'neet', 'surgery', 'surgeon'],
  },

  {
    id: 'bams_doctor',
    name: 'Ayurvedic Doctor (BAMS)',
    domain: 'medical',
    difficulty: 6,
    stress_level: 5,
    cost_range_inr: [5, 30],
    cost_range_usd: [20, 100],
    roi_score: 5,
    years_to_establish: 6,
    required_skills: ['Biology', 'Chemistry', 'Herbal Knowledge', 'Patient Care'],
    required_exams: [
      { name: 'NEET-UG', difficulty: 8, attempts_per_year: 1, eligibility: 'Class 12 (PCB)' },
    ],
    institutions_india: [
      { name: 'Banaras Hindu University (Ayurveda)', location: 'Varanasi', rank: 1, type: 'government', annual_cost_inr: 0.5 },
      { name: 'DY Patil Ayurved College', location: 'Pune', rank: 5, type: 'private', annual_cost_inr: 3 },
    ],
    institutions_abroad: [],
    paths: {
      safe: {
        label: 'Safe — State BAMS College',
        description: 'NEET 300+ for state BAMS admissions.',
        target_exams: ['NEET-UG'],
        institutions: [{ name: 'State BAMS Colleges', location: 'Various', type: 'government', annual_cost_inr: 0.8 }],
        timeline_years: 6,
        cost_inr_lakhs: 8,
        expected_salary_lpa: 5,
        roi_score: 5,
      },
      balanced: {
        label: 'Balanced — BHU/Top BAMS + Private Practice',
        description: 'Top BAMS college with a modernization approach.',
        target_exams: ['NEET-UG'],
        institutions: [{ name: 'BHU Ayurveda', location: 'Varanasi', type: 'government', annual_cost_inr: 0.5 }],
        timeline_years: 6,
        cost_inr_lakhs: 5,
        expected_salary_lpa: 8,
        roi_score: 5,
      },
      aggressive: {
        label: 'Aggressive — BAMS + Integrative Medicine Abroad',
        description: 'BAMS + Masters in Integrative Medicine (US/UK).',
        target_exams: ['NEET-UG'],
        institutions: [{ name: 'BHU → UK Integrative Medicine', location: 'Multiple', type: 'international', annual_cost_usd: 25 }],
        timeline_years: 8,
        cost_inr_lakhs: 40,
        expected_salary_lpa: 20,
        roi_score: 6,
      },
    },
    alternatives: ['mbbs_doctor', 'nutritionist', 'yoga_therapist'],
    sports_compatible: true,
    description: 'Holistic healing through Ayurvedic medicine.',
    tags: ['ayurveda', 'bams', 'alternative medicine', 'naturopathy', 'herbal'],
  },

  // ─────────────── SPORTS ───────────────
  {
    id: 'professional_cricketer',
    name: 'Professional Cricketer',
    domain: 'sports',
    difficulty: 9,
    stress_level: 8,
    cost_range_inr: [5, 50],
    cost_range_usd: [20, 200],
    roi_score: 9,
    years_to_establish: 8,
    required_skills: ['Cricket Techniques', 'Fitness', 'Mental Toughness', 'Tactical Awareness'],
    required_exams: [],
    institutions_india: [
      { name: 'MRF Pace Foundation', location: 'Chennai', rank: 1, type: 'private', annual_cost_inr: 3 },
      { name: 'VCA Cricket Academy', location: 'Nagpur', rank: 2, type: 'private', annual_cost_inr: 2 },
      { name: 'BCCI National Cricket Academy', location: 'Bangalore', rank: 1, type: 'government', annual_cost_inr: 0 },
    ],
    institutions_abroad: [
      { name: 'England Cricket Board (Scholarship)', location: 'England', type: 'international' },
      { name: 'Cricket Australia Development Programs', location: 'Australia', type: 'international' },
    ],
    paths: {
      safe: {
        label: 'Safe — State Team + Sports Quota Education',
        description: 'District → State team pathway with sports quota in university.',
        target_exams: [],
        institutions: [{ name: 'State Cricket Association', location: 'State HQ', type: 'government', annual_cost_inr: 1 }],
        timeline_years: 8,
        cost_inr_lakhs: 10,
        expected_salary_lpa: 5,
        roi_score: 5,
      },
      balanced: {
        label: 'Balanced — Ranji Trophy + IPL Aspirant',
        description: 'State team → Ranji representation → IPL auction.',
        target_exams: [],
        institutions: [{ name: 'BCCI NCA', location: 'Bangalore', type: 'government', annual_cost_inr: 0 }],
        timeline_years: 8,
        cost_inr_lakhs: 20,
        expected_salary_lpa: 30,
        roi_score: 8,
      },
      aggressive: {
        label: 'Aggressive — India Test Team',
        description: 'Elite pathway targeting Indian national team.',
        target_exams: [],
        institutions: [{ name: 'NCA + Elite Academy', location: 'Bangalore', type: 'government', annual_cost_inr: 0 }],
        timeline_years: 10,
        cost_inr_lakhs: 30,
        expected_salary_lpa: 200,
        roi_score: 10,
      },
    },
    alternatives: ['sports_coach', 'sports_journalist', 'sports_manager', 'physical_education_teacher'],
    sports_compatible: true,
    description: 'Play cricket at professional/national levels.',
    tags: ['cricket', 'ipl', 'bcci', 'batsman', 'bowler', 'cricketer', 'sports'],
  },

  {
    id: 'professional_athlete',
    name: 'Professional Athlete (Track & Field)',
    domain: 'sports',
    difficulty: 9,
    stress_level: 7,
    cost_range_inr: [3, 30],
    cost_range_usd: [10, 150],
    roi_score: 7,
    years_to_establish: 10,
    required_skills: ['Physical Conditioning', 'Mental Toughness', 'Technical Form'],
    required_exams: [],
    institutions_india: [
      { name: 'Sports Authority of India (SAI)', location: 'Multiple', rank: 1, type: 'government', annual_cost_inr: 0 },
      { name: 'Army Sports Institute', location: 'Pune', rank: 2, type: 'government', annual_cost_inr: 0 },
    ],
    institutions_abroad: [
      { name: 'USATF Developmental Programs', location: 'USA', type: 'international' },
    ],
    paths: {
      safe: {
        label: 'Safe — State Athletics + Army/Police Job',
        description: 'Athletics quota in government jobs (Army, Police, Railway).',
        target_exams: [],
        institutions: [{ name: 'SAI Training Centers', location: 'Multiple', type: 'government', annual_cost_inr: 0 }],
        timeline_years: 6,
        cost_inr_lakhs: 3,
        expected_salary_lpa: 6,
        roi_score: 6,
      },
      balanced: {
        label: 'Balanced — National Championships + Asian Games',
        description: 'National level athlete targeting Asian/Commonwealth Games.',
        target_exams: [],
        institutions: [{ name: 'SAI + State Academy', location: 'Multiple', type: 'government', annual_cost_inr: 0 }],
        timeline_years: 8,
        cost_inr_lakhs: 10,
        expected_salary_lpa: 12,
        roi_score: 7,
      },
      aggressive: {
        label: 'Aggressive — Olympics',
        description: 'Olympic qualification through AFI pipeline.',
        target_exams: [],
        institutions: [{ name: 'SAI TOPS Scheme + Foreign Coach', location: 'Multiple', type: 'government', annual_cost_inr: 0 }],
        timeline_years: 10,
        cost_inr_lakhs: 20,
        expected_salary_lpa: 50,
        roi_score: 9,
      },
    },
    alternatives: ['sports_coach', 'physical_education_teacher', 'sports_physiotherapist'],
    sports_compatible: true,
    description: 'Compete as a professional track and field athlete.',
    tags: ['athletics', 'running', 'sports', 'track', 'field', 'olympics', 'sprint', 'marathon'],
  },

  {
    id: 'sports_coach',
    name: 'Sports Coach / Trainer',
    domain: 'sports',
    difficulty: 5,
    stress_level: 4,
    cost_range_inr: [2, 20],
    cost_range_usd: [10, 80],
    roi_score: 5,
    years_to_establish: 5,
    required_skills: ['Sport Knowledge', 'Communication', 'Psychology', 'Fitness Assessment'],
    required_exams: [
      { name: 'NSNIS / SAI Coach Certification', difficulty: 4, attempts_per_year: 2, eligibility: '10+2' },
    ],
    institutions_india: [
      { name: 'LNIPE (Lakshmibai National Institute of Physical Education)', location: 'Gwalior', rank: 1, type: 'government', annual_cost_inr: 0.5 },
      { name: 'SAI Coaching Center', location: 'Multiple', rank: 2, type: 'government', annual_cost_inr: 0 },
    ],
    institutions_abroad: [],
    paths: {
      safe: {
        label: 'Safe — School/College Coach',
        description: 'NIS diploma + coaching at school/college level.',
        target_exams: ['NIS Diploma'],
        institutions: [{ name: 'LNIPE', location: 'Gwalior', type: 'government', annual_cost_inr: 0.5 }],
        timeline_years: 3,
        cost_inr_lakhs: 2,
        expected_salary_lpa: 4,
        roi_score: 5,
      },
      balanced: {
        label: 'Balanced — District/State Level Coaching',
        description: 'Sports science degree + state-level coaching career.',
        target_exams: ['NIS Diploma'],
        institutions: [{ name: 'LNIPE / State Sports Uni', location: 'Various', type: 'government', annual_cost_inr: 1 }],
        timeline_years: 4,
        cost_inr_lakhs: 5,
        expected_salary_lpa: 7,
        roi_score: 5,
      },
      aggressive: {
        label: 'Aggressive — International Certified Coach',
        description: 'International coaching certification (UEFA, ICC) + elite academy.',
        target_exams: ['International Coaching Certificate'],
        institutions: [{ name: 'International Academy (Online + Live)', location: 'Multiple', type: 'international', annual_cost_usd: 5 }],
        timeline_years: 6,
        cost_inr_lakhs: 15,
        expected_salary_lpa: 20,
        roi_score: 7,
      },
    },
    alternatives: ['physical_education_teacher', 'sports_manager', 'fitness_trainer'],
    sports_compatible: true,
    description: 'Train and develop athletes to reach their peak potential.',
    tags: ['coaching', 'trainer', 'sports training', 'fitness', 'physical education'],
  },

  // ─────────────── COMMERCE & BUSINESS ───────────────
  {
    id: 'chartered_accountant',
    name: 'Chartered Accountant (CA)',
    domain: 'commerce_business',
    difficulty: 8,
    stress_level: 8,
    cost_range_inr: [2, 15],
    cost_range_usd: [10, 80],
    roi_score: 8,
    years_to_establish: 5,
    required_skills: ['Mathematics', 'Financial Analysis', 'Tax Laws', 'Auditing'],
    required_exams: [
      { name: 'CA Foundation', difficulty: 6, attempts_per_year: 2, eligibility: 'Class 12' },
      { name: 'CA Intermediate', difficulty: 8, attempts_per_year: 2, eligibility: 'CA Foundation' },
      { name: 'CA Final', difficulty: 9, attempts_per_year: 2, eligibility: 'CA Inter + Articleship' },
    ],
    institutions_india: [
      { name: 'ICAI (Institute of Chartered Accountants of India)', location: 'Pan India', rank: 1, type: 'government', annual_cost_inr: 0.2 },
    ],
    institutions_abroad: [
      { name: 'ACCA (UK)', location: 'UK / Global', rank: 1, type: 'international', annual_cost_usd: 3 },
      { name: 'CPA (USA)', location: 'USA / Global', rank: 2, type: 'international', annual_cost_usd: 2 },
    ],
    paths: {
      safe: {
        label: 'Safe — CA + Industry Job',
        description: 'Complete CA and join corporate finance or Big 4 firms.',
        target_exams: ['CA Foundation', 'CA Inter', 'CA Final'],
        institutions: [{ name: 'ICAI', location: 'Pan India', type: 'government', annual_cost_inr: 0.2 }],
        timeline_years: 5,
        cost_inr_lakhs: 3,
        expected_salary_lpa: 10,
        roi_score: 8,
      },
      balanced: {
        label: 'Balanced — CA + CFA (US)',
        description: 'CA + CFA for investment banking and financial consulting.',
        target_exams: ['CA Foundation', 'CA Inter', 'CA Final', 'CFA Level 1-3'],
        institutions: [{ name: 'ICAI + CFA Institute', location: 'Pan India', type: 'government', annual_cost_inr: 0.3 }],
        timeline_years: 6,
        cost_inr_lakhs: 5,
        expected_salary_lpa: 25,
        roi_score: 9,
      },
      aggressive: {
        label: 'Aggressive — Big 4 Partner / Investment Banking',
        description: 'CA → Big 4 (Deloitte/EY/PWC) partner track or IB.',
        target_exams: ['CA Foundation', 'CA Inter', 'CA Final'],
        institutions: [{ name: 'ICAI + MBA IIM (later)', location: 'Pan India', type: 'government', annual_cost_inr: 0.2 }],
        timeline_years: 10,
        cost_inr_lakhs: 25,
        expected_salary_lpa: 60,
        roi_score: 10,
      },
    },
    alternatives: ['financial_analyst', 'investment_banker', 'tax_consultant', 'mba_finance'],
    sports_compatible: false,
    description: 'Professional accountant handling audits, taxation, and financial advisory.',
    tags: ['ca', 'accounting', 'finance', 'audit', 'tax', 'chartered accountant', 'big 4'],
  },

  {
    id: 'entrepreneur',
    name: 'Entrepreneur / Startup Founder',
    domain: 'commerce_business',
    difficulty: 9,
    stress_level: 10,
    cost_range_inr: [2, 100],
    cost_range_usd: [5, 500],
    roi_score: 9,
    years_to_establish: 7,
    required_skills: ['Leadership', 'Problem Solving', 'Communication', 'Resilience', 'Sales'],
    required_exams: [],
    institutions_india: [
      { name: 'IIM Ahmedabad (MBA)', location: 'Ahmedabad', rank: 1, type: 'government', annual_cost_inr: 24 },
      { name: 'IIT Delhi (PGDM)', location: 'Delhi', rank: 2, type: 'government', annual_cost_inr: 10 },
      { name: 'ISB Hyderabad', location: 'Hyderabad', rank: 5, type: 'private', annual_cost_inr: 40 },
    ],
    institutions_abroad: [
      { name: 'Harvard Business School', location: 'Boston, USA', rank: 1, type: 'international', annual_cost_usd: 110 },
      { name: 'Stanford GSB', location: 'Stanford, USA', rank: 2, type: 'international', annual_cost_usd: 110 },
    ],
    paths: {
      safe: {
        label: 'Safe — Startup in Known Domain After Education',
        description: 'Get industry experience, build skills, then launch a startup.',
        target_exams: ['CAT / GMAT (Optional)'],
        institutions: [{ name: 'Any reputed Uni', location: 'Various', type: 'private', annual_cost_inr: 5 }],
        timeline_years: 7,
        cost_inr_lakhs: 10,
        expected_salary_lpa: 20,
        roi_score: 7,
      },
      balanced: {
        label: 'Balanced — IIM MBA → Corporate → Startup',
        description: 'IIM MBA, corporate leadership, then launch a well-funded startup.',
        target_exams: ['CAT'],
        institutions: [{ name: 'IIM Bangalore/Calcutta', location: 'Various', type: 'government', annual_cost_inr: 25 }],
        timeline_years: 8,
        cost_inr_lakhs: 30,
        expected_salary_lpa: 50,
        roi_score: 9,
      },
      aggressive: {
        label: 'Aggressive — Dropout + Build from Class 12',
        description: 'Jump directly into entrepreneurship after school.',
        target_exams: [],
        institutions: [{ name: 'Incubators / Y Combinator', location: 'Various', type: 'international', annual_cost_inr: 0 }],
        timeline_years: 5,
        cost_inr_lakhs: 5,
        expected_salary_lpa: 100,
        roi_score: 8,
      },
    },
    alternatives: ['product_manager', 'mba_finance', 'venture_capitalist'],
    sports_compatible: false,
    description: 'Build and scale your own startup or business venture.',
    tags: ['startup', 'founder', 'entrepreneur', 'business', 'venture', 'ceo', 'company'],
  },

  // ─────────────── GOVERNMENT & LAW ───────────────
  {
    id: 'ias_ips_officer',
    name: 'IAS / IPS Officer (Civil Services)',
    domain: 'government_law',
    difficulty: 10,
    stress_level: 8,
    cost_range_inr: [1, 10],
    cost_range_usd: [5, 50],
    roi_score: 6,
    years_to_establish: 6,
    required_skills: ['General Knowledge', 'Essay Writing', 'Critical Thinking', 'Leadership', 'Ethics'],
    required_exams: [
      { name: 'UPSC Prelims', difficulty: 8, attempts_per_year: 1, eligibility: 'Any graduate' },
      { name: 'UPSC Mains', difficulty: 9, attempts_per_year: 1, eligibility: 'UPSC Prelims qualifier' },
      { name: 'UPSC Interview', difficulty: 8, attempts_per_year: 1, eligibility: 'UPSC Mains qualifier' },
    ],
    institutions_india: [
      { name: 'Drishti IAS', location: 'Delhi', rank: 1, type: 'private', annual_cost_inr: 1.5 },
      { name: 'Vision IAS', location: 'Delhi', rank: 2, type: 'private', annual_cost_inr: 1.2 },
      { name: 'LBSNAA (Training after selection)', location: 'Mussoorie', rank: 1, type: 'government', annual_cost_inr: 0 },
    ],
    institutions_abroad: [],
    paths: {
      safe: {
        label: 'Safe — State PSC / Group A Services',
        description: 'Target State PCS (state civil services) as a stepping stone.',
        target_exams: ['State PCS'],
        institutions: [{ name: 'State Academy + Self Study', location: 'Various', type: 'government', annual_cost_inr: 0.5 }],
        timeline_years: 4,
        cost_inr_lakhs: 3,
        expected_salary_lpa: 8,
        roi_score: 6,
      },
      balanced: {
        label: 'Balanced — IFS/IRS/IPS through UPSC',
        description: 'Target IPS or IRS (Revenue/Taxation) through UPSC.',
        target_exams: ['UPSC CSE'],
        institutions: [{ name: 'Coaching Institute + Self Study', location: 'Delhi', type: 'private', annual_cost_inr: 2 }],
        timeline_years: 5,
        cost_inr_lakhs: 6,
        expected_salary_lpa: 12,
        roi_score: 6,
      },
      aggressive: {
        label: 'Aggressive — IAS (Rank 1–100)',
        description: 'Full preparation for top-100 IAS rank.',
        target_exams: ['UPSC CSE (AIR 1-100 target)'],
        institutions: [{ name: 'Top Coaching + Optional Subject Expert', location: 'Delhi/Online', type: 'private', annual_cost_inr: 3 }],
        timeline_years: 6,
        cost_inr_lakhs: 8,
        expected_salary_lpa: 15,
        roi_score: 7,
      },
    },
    alternatives: ['lawyer', 'defense_officer', 'policy_researcher'],
    sports_compatible: false,
    description: 'Serve the nation in policy-making and administration.',
    tags: ['ias', 'ips', 'upsc', 'civil services', 'government', 'officer', 'admin', 'collector'],
  },

  {
    id: 'lawyer',
    name: 'Lawyer / Advocate',
    domain: 'government_law',
    difficulty: 7,
    stress_level: 7,
    cost_range_inr: [5, 60],
    cost_range_usd: [30, 200],
    roi_score: 7,
    years_to_establish: 7,
    required_skills: ['Argumentation', 'Research', 'Writing', 'Critical Thinking', 'Ethics'],
    required_exams: [
      { name: 'CLAT', difficulty: 7, attempts_per_year: 1, eligibility: 'Class 12' },
      { name: 'AILET', difficulty: 8, attempts_per_year: 1, eligibility: 'Class 12' },
    ],
    institutions_india: [
      { name: 'NLS Bangalore (NLSIU)', location: 'Bangalore', rank: 1, type: 'government', annual_cost_inr: 1.5, acceptance_rate: 1 },
      { name: 'NALSAR Hyderabad', location: 'Hyderabad', rank: 2, type: 'government', annual_cost_inr: 1.2 },
      { name: 'NLU Delhi', location: 'Delhi', rank: 3, type: 'government', annual_cost_inr: 1 },
      { name: 'Symbiosis Law School', location: 'Pune', rank: 10, type: 'deemed', annual_cost_inr: 3 },
    ],
    institutions_abroad: [
      { name: 'Oxford University (Law)', location: 'Oxford, UK', rank: 1, type: 'international', annual_cost_usd: 35 },
      { name: 'Harvard Law School', location: 'Boston, USA', rank: 2, type: 'international', annual_cost_usd: 65 },
    ],
    paths: {
      safe: {
        label: 'Safe — State/Private Law School',
        description: 'Enroll in a state law university after Class 12.',
        target_exams: ['CLAT', 'State Law CET'],
        institutions: [{ name: 'State Law Universities', location: 'Various', type: 'government', annual_cost_inr: 1 }],
        timeline_years: 5,
        cost_inr_lakhs: 6,
        expected_salary_lpa: 6,
        roi_score: 6,
      },
      balanced: {
        label: 'Balanced — NLU + Corporate Law',
        description: 'Top NLU through CLAT → corporate law career in top firms.',
        target_exams: ['CLAT'],
        institutions: [
          { name: 'NALSAR / NLU Delhi', location: 'Various', type: 'government', annual_cost_inr: 1.5 },
        ],
        timeline_years: 6,
        cost_inr_lakhs: 10,
        expected_salary_lpa: 18,
        roi_score: 7,
      },
      aggressive: {
        label: 'Aggressive — NLSIU + Oxford LLM',
        description: 'Top NLU → Oxford/Harvard LLM → international law.',
        target_exams: ['CLAT (AIR 1-50)', 'LNAT (Oxford)'],
        institutions: [
          { name: 'NLS Bangalore', location: 'Bangalore', type: 'government', annual_cost_inr: 1.5 },
          { name: 'Oxford University Law', location: 'Oxford, UK', type: 'international', annual_cost_usd: 35 },
        ],
        timeline_years: 7,
        cost_inr_lakhs: 50,
        expected_salary_lpa: 50,
        roi_score: 9,
      },
    },
    alternatives: ['ias_ips_officer', 'judge', 'policy_researcher', 'legal_consultant'],
    sports_compatible: false,
    description: 'Practice law in courts or corporate legal departments.',
    tags: ['law', 'lawyer', 'advocate', 'clat', 'legal', 'litigation', 'court', 'attorney'],
  },

  {
    id: 'defense_officer',
    name: 'Defence Officer (Army/Navy/Air Force)',
    domain: 'government_law',
    difficulty: 7,
    stress_level: 8,
    cost_range_inr: [0, 2],
    cost_range_usd: [0, 10],
    roi_score: 6,
    years_to_establish: 3,
    required_skills: ['Physical Fitness', 'Leadership', 'Discipline', 'Teamwork'],
    required_exams: [
      { name: 'NDA (National Defence Academy)', difficulty: 7, attempts_per_year: 2, eligibility: 'Class 12' },
      { name: 'CDS (Combined Defence Services)', difficulty: 7, attempts_per_year: 2, eligibility: 'Graduation' },
    ],
    institutions_india: [
      { name: 'National Defence Academy, Pune', location: 'Pune', rank: 1, type: 'government', annual_cost_inr: 0 },
      { name: 'Indian Military Academy, Dehradun', location: 'Dehradun', rank: 1, type: 'government', annual_cost_inr: 0 },
    ],
    institutions_abroad: [],
    paths: {
      safe: {
        label: 'Safe — Short Service Commission',
        description: 'SSC through CDS after graduation — 14 years of service.',
        target_exams: ['CDS'],
        institutions: [{ name: 'IMA/OTA', location: 'Dehradun/Chennai', type: 'government', annual_cost_inr: 0 }],
        timeline_years: 3,
        cost_inr_lakhs: 0,
        expected_salary_lpa: 8,
        roi_score: 6,
      },
      balanced: {
        label: 'Balanced — NDA → Permanent Commission',
        description: 'Join NDA after Class 12, get permanent commission.',
        target_exams: ['NDA'],
        institutions: [{ name: 'National Defence Academy', location: 'Pune', type: 'government', annual_cost_inr: 0 }],
        timeline_years: 5,
        cost_inr_lakhs: 0,
        expected_salary_lpa: 10,
        roi_score: 7,
      },
      aggressive: {
        label: 'Aggressive — IIT + Tech Entry (IAST)',
        description: 'IIT Engineering → Army tech entry as officer (specialized).',
        target_exams: ['JEE Advanced', 'NDA'],
        institutions: [{ name: 'IIT (Tech Entry)', location: 'Various IITs', type: 'government', annual_cost_inr: 2 }],
        timeline_years: 6,
        cost_inr_lakhs: 10,
        expected_salary_lpa: 18,
        roi_score: 7,
      },
    },
    alternatives: ['ias_ips_officer', 'police_officer', 'paramilitary'],
    sports_compatible: true,
    description: 'Serve in the Indian Armed Forces as a commissioned officer.',
    tags: ['army', 'navy', 'air force', 'defence', 'military', 'nda', 'officer', 'soldier'],
  },

  // ─────────────── ARTS & CREATIVE ───────────────
  {
    id: 'ux_designer',
    name: 'UX/UI Designer',
    domain: 'arts_creative',
    difficulty: 6,
    stress_level: 5,
    cost_range_inr: [3, 30],
    cost_range_usd: [20, 150],
    roi_score: 7,
    years_to_establish: 3,
    required_skills: ['Design Thinking', 'Visual Design', 'Prototyping', 'User Research'],
    required_exams: [],
    institutions_india: [
      { name: 'National Institute of Design (NID)', location: 'Ahmedabad', rank: 1, type: 'government', annual_cost_inr: 1.5, acceptance_rate: 1 },
      { name: 'Industrial Design Centre (IDC, IIT Bombay)', location: 'Mumbai', rank: 2, type: 'government', annual_cost_inr: 2 },
      { name: 'Srishti Institute of Art and Design', location: 'Bangalore', rank: 5, type: 'private', annual_cost_inr: 4 },
    ],
    institutions_abroad: [
      { name: 'Rhode Island School of Design', location: 'USA', rank: 2, type: 'international', annual_cost_usd: 55 },
      { name: 'Parsons School of Design', location: 'New York, USA', rank: 3, type: 'international', annual_cost_usd: 55 },
    ],
    paths: {
      safe: {
        label: 'Safe — Online Bootcamp + Freelancing',
        description: 'UCCD/Figma course + strong portfolio → freelance or agency.',
        target_exams: [],
        institutions: [{ name: 'Online UX Bootcamp (Coursera/DesignLab)', location: 'Online', type: 'private', annual_cost_inr: 0.5 }],
        timeline_years: 2,
        cost_inr_lakhs: 1,
        expected_salary_lpa: 6,
        roi_score: 7,
      },
      balanced: {
        label: 'Balanced — IDC/NID + Tech Company',
        description: 'NID or IDC degree → top tech companies.',
        target_exams: ['UCEED (for IDC)', 'NID DAT'],
        institutions: [
          { name: 'NID Ahmedabad', location: 'Ahmedabad', type: 'government', annual_cost_inr: 1.5 },
        ],
        timeline_years: 4,
        cost_inr_lakhs: 8,
        expected_salary_lpa: 18,
        roi_score: 8,
      },
      aggressive: {
        label: 'Aggressive — NID + Google/Apple',
        description: 'Top design school + internship at FAANG/global tech.',
        target_exams: ['UCEED', 'NID DAT'],
        institutions: [
          { name: 'IDC, IIT Bombay', location: 'Mumbai', type: 'government', annual_cost_inr: 2 },
        ],
        timeline_years: 4,
        cost_inr_lakhs: 10,
        expected_salary_lpa: 40,
        roi_score: 9,
      },
    },
    alternatives: ['graphic_designer', 'product_manager', 'architect'],
    sports_compatible: false,
    description: 'Design user interfaces and experiences for digital products.',
    tags: ['design', 'ux', 'ui', 'figma', 'product design', 'art', 'creative', 'visual'],
  },

  {
    id: 'content_creator',
    name: 'Content Creator / Digital Media',
    domain: 'arts_creative',
    difficulty: 6,
    stress_level: 5,
    cost_range_inr: [0.5, 10],
    cost_range_usd: [1, 30],
    roi_score: 6,
    years_to_establish: 3,
    required_skills: ['Creativity', 'Video Production', 'Marketing', 'Writing', 'Social Media'],
    required_exams: [],
    institutions_india: [
      { name: 'Whistling Woods International', location: 'Mumbai', rank: 1, type: 'private', annual_cost_inr: 5 },
      { name: 'Symbiosis Institute of Media & Communication', location: 'Pune', rank: 2, type: 'deemed', annual_cost_inr: 3 },
    ],
    institutions_abroad: [],
    paths: {
      safe: {
        label: 'Safe — Digital Marketing + Content Strategy',
        description: 'Mass communication degree + YouTube/blog monetization.',
        target_exams: [],
        institutions: [{ name: 'Mass Communication / Journalism College', location: 'Various', type: 'private', annual_cost_inr: 1.5 }],
        timeline_years: 3,
        cost_inr_lakhs: 5,
        expected_salary_lpa: 6,
        roi_score: 6,
      },
      balanced: {
        label: 'Balanced — Multi-Platform Creator',
        description: 'Build audience on YouTube + Brand deals + freelance.',
        target_exams: [],
        institutions: [{ name: 'Self-built skillset', location: 'Online', type: 'private', annual_cost_inr: 0.5 }],
        timeline_years: 3,
        cost_inr_lakhs: 2,
        expected_salary_lpa: 15,
        roi_score: 7,
      },
      aggressive: {
        label: 'Aggressive — 1M+ Creator + Brand',
        description: 'Full-time content creation, build personal brand, multiple revenue streams.',
        target_exams: [],
        institutions: [{ name: 'Self-created + Mentorship', location: 'Online', type: 'private', annual_cost_inr: 0.5 }],
        timeline_years: 4,
        cost_inr_lakhs: 2,
        expected_salary_lpa: 50,
        roi_score: 7,
      },
    },
    alternatives: ['journalist', 'filmmaker', 'graphic_designer', 'social_media_manager'],
    sports_compatible: true,
    description: 'Build an audience and monetize digital content creation.',
    tags: ['youtube', 'content', 'creator', 'instagram', 'social media', 'film', 'video', 'blogging'],
  },

  // ─────────────── EMERGING / HYBRID ───────────────
  {
    id: 'product_manager',
    name: 'Product Manager (Tech)',
    domain: 'emerging_hybrid',
    difficulty: 7,
    stress_level: 7,
    cost_range_inr: [5, 60],
    cost_range_usd: [30, 200],
    roi_score: 9,
    years_to_establish: 6,
    required_skills: ['Strategic Thinking', 'Data Analysis', 'Communication', 'User Psychology', 'Technical Understanding'],
    required_exams: [
      { name: 'JEE Main (for CS undergrad)', difficulty: 7, attempts_per_year: 2, eligibility: 'Class 12' },
      { name: 'CAT (for MBA)', difficulty: 8, attempts_per_year: 1, eligibility: 'Graduation' },
    ],
    institutions_india: [
      { name: 'IIT Bombay (CS with PM minor)', location: 'Mumbai', rank: 118, type: 'government', annual_cost_inr: 2.5 },
      { name: 'IIM Ahmedabad (MBA)', location: 'Ahmedabad', rank: 1, type: 'government', annual_cost_inr: 24 },
    ],
    institutions_abroad: [
      { name: 'Stanford (CS + MBA)', location: 'USA', rank: 2, type: 'international', annual_cost_usd: 110 },
    ],
    paths: {
      safe: {
        label: 'Safe — CS Degree + APM Program',
        description: 'CS degree + Associate PM (APM) program at a tech company.',
        target_exams: ['JEE Main'],
        institutions: [{ name: 'Any CS college + APM at FAANG', location: 'Various', type: 'private', annual_cost_inr: 3 }],
        timeline_years: 6,
        cost_inr_lakhs: 15,
        expected_salary_lpa: 25,
        roi_score: 8,
      },
      balanced: {
        label: 'Balanced — IIT CS + IIM MBA',
        description: 'IIT for CS foundation, IIM for business skills → PM at top startup.',
        target_exams: ['JEE Advanced', 'CAT'],
        institutions: [
          { name: 'IIT (CS)', location: 'IITs', type: 'government', annual_cost_inr: 2.5 },
          { name: 'IIM Bangalore', location: 'Bangalore', type: 'government', annual_cost_inr: 25 },
        ],
        timeline_years: 8,
        cost_inr_lakhs: 35,
        expected_salary_lpa: 50,
        roi_score: 9,
      },
      aggressive: {
        label: 'Aggressive — FAANG PM (Global)',
        description: 'Top CS school → FAANG APM → Senior PM at top-tier company.',
        target_exams: ['JEE Advanced / SAT'],
        institutions: [
          { name: 'IIT / Stanford / MIT', location: 'India/USA', type: 'government', annual_cost_inr: 2.5 },
        ],
        timeline_years: 8,
        cost_inr_lakhs: 40,
        expected_salary_lpa: 120,
        roi_score: 10,
      },
    },
    alternatives: ['entrepreneur', 'software_engineer', 'data_scientist', 'ux_designer'],
    sports_compatible: false,
    description: 'Lead product strategy and development at tech companies.',
    tags: ['pm', 'product', 'product manager', 'tech', 'strategy', 'startup'],
  },

  {
    id: 'forensic_scientist',
    name: 'Forensic Scientist',
    domain: 'emerging_hybrid',
    difficulty: 7,
    stress_level: 6,
    cost_range_inr: [4, 25],
    cost_range_usd: [20, 100],
    roi_score: 6,
    years_to_establish: 6,
    required_skills: ['Biology', 'Chemistry', 'Analytical Thinking', 'Attention to Detail'],
    required_exams: [
      { name: 'B.Sc Forensic Science Entrance', difficulty: 5, attempts_per_year: 1, eligibility: 'Class 12 (PCB/PCM)' },
    ],
    institutions_india: [
      { name: 'Gujarat Forensic Sciences University', location: 'Gandhinagar', rank: 1, type: 'government', annual_cost_inr: 1 },
      { name: 'Lok Nayak Jai Prakash Institute (LNJP)', location: 'Delhi', rank: 2, type: 'government', annual_cost_inr: 0.5 },
    ],
    institutions_abroad: [
      { name: "King's College London (Forensic Science)", location: 'London, UK', rank: 27, type: 'international', annual_cost_usd: 30 },
    ],
    paths: {
      safe: {
        label: 'Safe — B.Sc + Government Lab',
        description: 'B.Sc Forensic Science + government lab or police forensics.',
        target_exams: ['GFSU Entrance'],
        institutions: [{ name: 'GFSU / State Forensic Labs', location: 'Various', type: 'government', annual_cost_inr: 1 }],
        timeline_years: 4,
        cost_inr_lakhs: 4,
        expected_salary_lpa: 5,
        roi_score: 5,
      },
      balanced: {
        label: 'Balanced — M.Sc Forensic + CBI/NIA',
        description: 'M.Sc + elite investigative agencies (CBI, NIA, NCB).',
        target_exams: ['M.Sc Entrance'],
        institutions: [{ name: 'GFSU + CBI Training', location: 'Various', type: 'government', annual_cost_inr: 2 }],
        timeline_years: 6,
        cost_inr_lakhs: 6,
        expected_salary_lpa: 10,
        roi_score: 6,
      },
      aggressive: {
        label: 'Aggressive — International Forensics Agency',
        description: 'M.Sc abroad + work at Interpol/Scotland Yard.',
        target_exams: ['IELTS', 'GRE'],
        institutions: [{ name: "King's College London", location: 'London', type: 'international', annual_cost_usd: 30 }],
        timeline_years: 7,
        cost_inr_lakhs: 40,
        expected_salary_lpa: 25,
        roi_score: 7,
      },
    },
    alternatives: ['mbbs_doctor', 'ias_ips_officer', 'researcher'],
    sports_compatible: false,
    description: 'Apply scientific methods to solve crimes and legal cases.',
    tags: ['forensic', 'crime', 'investigation', 'forensics', 'cbi', 'detective'],
  },
];

// ─── DREAM JOB SYNONYM MAP ───────────────────────────────────

export const DREAM_JOB_MAP: Record<string, string> = {
  // Tech
  'coder': 'software_engineer', 'programmer': 'software_engineer', 'developer': 'software_engineer',
  'software dev': 'software_engineer', 'full stack': 'software_engineer', 'app developer': 'software_engineer',
  'ai engineer': 'data_scientist', 'ml engineer': 'data_scientist', 'machine learning': 'data_scientist',
  'data analyst': 'data_scientist', 'data science': 'data_scientist', 'deep learning': 'data_scientist',
  'ethical hacker': 'cybersecurity_analyst', 'hacker': 'cybersecurity_analyst', 'security analyst': 'cybersecurity_analyst',
  'web developer': 'software_engineer', 'backend developer': 'software_engineer', 'frontend developer': 'software_engineer',
  // Medical
  'doctor': 'mbbs_doctor', 'physician': 'mbbs_doctor', 'surgeon': 'mbbs_doctor',
  'mbbs': 'mbbs_doctor', 'medicine': 'mbbs_doctor', 'neet': 'mbbs_doctor',
  'ayurvedic': 'bams_doctor', 'bams': 'bams_doctor',
  // Sports
  'cricketer': 'professional_cricketer', 'cricket player': 'professional_cricketer', 'ipl player': 'professional_cricketer',
  'athlete': 'professional_athlete', 'runner': 'professional_athlete', 'sprinter': 'professional_athlete',
  'coach': 'sports_coach', 'trainer': 'sports_coach',
  // Business
  'ca': 'chartered_accountant', 'accountant': 'chartered_accountant', 'auditor': 'chartered_accountant',
  'startup founder': 'entrepreneur', 'businessman': 'entrepreneur', 'ceo': 'entrepreneur',
  // Government
  'ias': 'ias_ips_officer', 'ips': 'ias_ips_officer', 'civil servant': 'ias_ips_officer', 'collector': 'ias_ips_officer',
  'advocate': 'lawyer', 'barrister': 'lawyer', 'judge': 'lawyer', 'legal': 'lawyer',
  'army': 'defense_officer', 'navy': 'defense_officer', 'air force': 'defense_officer', 'soldier': 'defense_officer',
  // Creative
  'designer': 'ux_designer', 'ux': 'ux_designer', 'product designer': 'ux_designer',
  'youtuber': 'content_creator', 'influencer': 'content_creator', 'blogger': 'content_creator',
  // Emerging
  'pm': 'product_manager', 'product management': 'product_manager',
  'forensics': 'forensic_scientist', 'crime investigation': 'forensic_scientist',
};

export function getCareerById(id: string): Career | undefined {
  return CAREER_DATABASE.find(c => c.id === id);
}

export function getCareersByDomain(domain: string): Career[] {
  return CAREER_DATABASE.filter(c => c.domain === domain);
}

export function searchCareers(query: string): Career[] {
  const q = query.toLowerCase();
  return CAREER_DATABASE.filter(c =>
    c.name.toLowerCase().includes(q) ||
    c.tags.some(t => t.includes(q)) ||
    c.description.toLowerCase().includes(q)
  );
}
