// ============================================================
// PATHFORGE AI — SCHOLARSHIP DATABASE
// 20+ real scholarships with detailed eligibility data
// ============================================================

import { Scholarship } from './types';

export const SCHOLARSHIP_DATABASE: Scholarship[] = [
  // ─── INDIA — GOVERNMENT / MERIT ────────────────────────────
  {
    id: 'inspire_scholarship',
    name: 'INSPIRE Scholarship (SHE)',
    provider: 'Department of Science & Technology, Govt of India',
    country: 'India',
    region: 'india',
    eligibility: {
      min_performance: '85_95',
      target_fields: ['stem', 'research'],
      requires_entrance_exam: false,
      requires_research: false,
      requires_community_service: false,
    },
    coverage: 'partial_50',
    coverage_details: '₹80,000/year scholarship for 5 years pursuing BSc/BS/Integrated MS in Natural Sciences',
    amount_inr_lakhs: 4,
    difficulty: 5,
    acceptance_rate_percent: 25,
    deadline_month: 'October',
    required_documents: ['Class 12 marksheet', 'JEE/NEET rank card', 'Income certificate'],
    description: 'For top 1% performers in Class 12 or JEE/NEET qualifiers pursuing basic/natural sciences.',
    tags: ['india', 'government', 'science', 'merit', 'stem'],
  },
  {
    id: 'kvpy_fellowship',
    name: 'KVPY Fellowship (now integrated with INSPIRE)',
    provider: 'Indian Institute of Science (IISc)',
    country: 'India',
    region: 'india',
    eligibility: {
      min_performance: '85_95',
      target_fields: ['stem', 'research'],
      requires_entrance_exam: true,
      requires_research: false,
      requires_community_service: false,
    },
    coverage: 'partial_50',
    coverage_details: '₹5,000–7,000/month fellowship + contingency grant for research aptitude students',
    amount_inr_lakhs: 4.2,
    difficulty: 7,
    acceptance_rate_percent: 5,
    deadline_month: 'August',
    required_documents: ['KVPY score card', 'Class 10/12 marksheet', 'Research statement'],
    description: 'Prestigious science fellowship for students showing exceptional research aptitude.',
    tags: ['india', 'research', 'science', 'fellowship', 'iisc'],
  },
  {
    id: 'pm_vidyalakshmi',
    name: 'PM Vidyalakshmi Education Loan Scheme',
    provider: 'Government of India',
    country: 'India',
    region: 'india',
    eligibility: {
      min_performance: '60_75',
      max_family_income_lpa: 8,
      target_fields: ['general'],
      requires_entrance_exam: false,
      requires_research: false,
      requires_community_service: false,
    },
    coverage: 'full',
    coverage_details: 'Interest-free education loans up to ₹10L for families earning < ₹8 LPA; subsidized up to ₹25L',
    amount_inr_lakhs: 25,
    difficulty: 3,
    acceptance_rate_percent: 60,
    deadline_month: 'Year-round',
    required_documents: ['Admission letter', 'Income certificate', 'Aadhaar', 'Bank details'],
    description: 'Government-backed interest-free education loan for economically weaker students.',
    tags: ['india', 'loan', 'government', 'need-based', 'financial-aid'],
  },
  {
    id: 'central_sector_scholarship',
    name: 'Central Sector Scheme of Scholarships (CSSS)',
    provider: 'Ministry of Education, Govt of India',
    country: 'India',
    region: 'india',
    eligibility: {
      min_performance: '75_85',
      max_family_income_lpa: 8,
      target_fields: ['general'],
      requires_entrance_exam: false,
      requires_research: false,
      requires_community_service: false,
    },
    coverage: 'partial_25',
    coverage_details: '₹10,000–20,000/year for graduation; ₹20,000/year for post-graduation',
    amount_inr_lakhs: 1,
    difficulty: 4,
    acceptance_rate_percent: 35,
    deadline_month: 'November',
    required_documents: ['Class 12 marksheet (80th percentile+)', 'Income certificate', 'Bank details'],
    description: 'For students in top 20th percentile of Class 12 boards with family income < ₹8 LPA.',
    tags: ['india', 'government', 'merit-cum-means', 'undergraduate'],
  },
  {
    id: 'ntse_scholarship',
    name: 'NTSE Scholarship',
    provider: 'NCERT',
    country: 'India',
    region: 'india',
    eligibility: {
      min_performance: '85_95',
      target_fields: ['general'],
      class_restriction: [10],
      requires_entrance_exam: true,
      requires_research: false,
      requires_community_service: false,
    },
    coverage: 'partial_25',
    coverage_details: '₹1,250/month (Class 11-12); ₹2,000/month (UG/PG); ₹8,000+stipend (PhD)',
    amount_inr_lakhs: 1.5,
    difficulty: 8,
    acceptance_rate_percent: 1,
    deadline_month: 'November',
    required_documents: ['NTSE Stage 1 & 2 results', 'School verification'],
    description: 'Highly prestigious talent search exam. NTSE scholars are recognized across India.',
    tags: ['india', 'merit', 'talent-search', 'class-10', 'prestigious'],
  },
  {
    id: 'iit_fee_waiver',
    name: 'IIT Fee Waiver Scheme',
    provider: 'Indian Institutes of Technology',
    country: 'India',
    region: 'india',
    eligibility: {
      min_performance: '85_95',
      max_family_income_lpa: 5,
      target_fields: ['stem'],
      requires_entrance_exam: true,
      requires_research: false,
      requires_community_service: false,
    },
    coverage: 'full',
    coverage_details: 'Full tuition waiver for family income < ₹1 LPA; 66% waiver for < ₹5 LPA',
    amount_inr_lakhs: 10,
    difficulty: 9,
    acceptance_rate_percent: 2,
    deadline_month: 'June',
    required_documents: ['JEE Advanced rank card', 'Income certificate', 'Caste certificate (if applicable)'],
    description: 'Automatic fee reduction for JEE Advanced qualifiers from economically weaker backgrounds.',
    tags: ['india', 'iit', 'fee-waiver', 'need-based', 'engineering'],
  },
  {
    id: 'aicte_pragati',
    name: 'AICTE Pragati Scholarship for Girls',
    provider: 'AICTE',
    country: 'India',
    region: 'india',
    eligibility: {
      min_performance: '60_75',
      max_family_income_lpa: 8,
      target_fields: ['stem'],
      requires_entrance_exam: false,
      requires_research: false,
      requires_community_service: false,
      gender_specific: 'female',
    },
    coverage: 'partial_50',
    coverage_details: '₹50,000/year for female students in AICTE-approved technical institutions',
    amount_inr_lakhs: 2,
    difficulty: 4,
    acceptance_rate_percent: 30,
    deadline_month: 'December',
    required_documents: ['AICTE institution admission', 'Income certificate', 'Gender certificate'],
    description: 'Empowering women in STEM with direct financial support.',
    tags: ['india', 'women', 'stem', 'technical', 'aicte'],
  },
  {
    id: 'kishore_vaigyanik',
    name: 'Kishore Vaigyanik Protsahan Yojana (KVPY)',
    provider: 'DST / IISc Bangalore',
    country: 'India',
    region: 'india',
    eligibility: {
      min_performance: '75_85',
      target_fields: ['stem', 'research'],
      requires_entrance_exam: true,
      requires_research: false,
      requires_community_service: false,
    },
    coverage: 'partial_50',
    coverage_details: 'Monthly fellowship ₹5,000-7,000 + annual contingency grant ₹20,000-28,000',
    amount_inr_lakhs: 3.5,
    difficulty: 7,
    acceptance_rate_percent: 4,
    deadline_month: 'July',
    required_documents: ['KVPY application', 'Aptitude test result', 'Interview score'],
    description: 'National fellowship to encourage students in pursuing research careers in basic sciences.',
    tags: ['india', 'research', 'fellowship', 'science', 'aptitude'],
  },

  // ─── USA — MERIT + NEED-BASED ──────────────────────────────
  {
    id: 'fulbright_nehru',
    name: 'Fulbright-Nehru Master\'s Fellowship',
    provider: 'United States-India Educational Foundation (USIEF)',
    country: 'USA',
    region: 'usa',
    eligibility: {
      min_performance: '75_85',
      target_fields: ['general', 'stem', 'arts', 'research'],
      country_restriction: 'India',
      requires_entrance_exam: true,
      requires_research: true,
      requires_community_service: true,
    },
    coverage: 'full',
    coverage_details: 'Full tuition, living stipend, airfare, health insurance, book allowance for US master\'s programs',
    amount_usd_thousands: 80,
    amount_inr_lakhs: 65,
    difficulty: 9,
    acceptance_rate_percent: 5,
    deadline_month: 'February',
    required_documents: ['SOP', '3 LORs', 'GRE/GMAT scores', 'TOEFL/IELTS', 'CV', 'Research proposal', 'Community service proof'],
    description: 'The most prestigious India-US exchange program. Fully funded master\'s at top US universities.',
    tags: ['usa', 'prestigious', 'fully-funded', 'masters', 'research'],
  },
  {
    id: 'stanford_knight_hennessy',
    name: 'Knight-Hennessy Scholars',
    provider: 'Stanford University',
    country: 'USA',
    region: 'usa',
    eligibility: {
      min_performance: '95_plus',
      target_fields: ['general', 'stem', 'law', 'medical'],
      requires_entrance_exam: true,
      requires_research: true,
      requires_community_service: true,
    },
    coverage: 'full',
    coverage_details: 'Full tuition, stipend, travel, and enrichment funding for any Stanford graduate program',
    amount_usd_thousands: 120,
    amount_inr_lakhs: 100,
    difficulty: 10,
    acceptance_rate_percent: 2,
    deadline_month: 'October',
    required_documents: ['SOP', '3 LORs', 'GRE/GMAT', 'Leadership portfolio', 'Video essays', 'Research publication list'],
    description: 'The world\'s most selective graduate scholarship. For visionary leaders with extraordinary potential.',
    tags: ['usa', 'stanford', 'elite', 'leadership', 'fully-funded'],
  },
  {
    id: 'mit_financial_aid',
    name: 'MIT Need-Based Financial Aid',
    provider: 'Massachusetts Institute of Technology',
    country: 'USA',
    region: 'usa',
    eligibility: {
      min_performance: '95_plus',
      target_fields: ['stem', 'research'],
      requires_entrance_exam: true,
      requires_research: false,
      requires_community_service: false,
    },
    coverage: 'full',
    coverage_details: 'MIT meets 100% demonstrated financial need. ~58% of students receive aid.',
    amount_usd_thousands: 75,
    amount_inr_lakhs: 62,
    difficulty: 10,
    acceptance_rate_percent: 4,
    deadline_month: 'January',
    required_documents: ['CSS Profile', 'FAFSA equivalent', 'Tax documents', 'SAT/ACT', 'LORs', 'Essays'],
    description: 'MIT is need-blind for international students and meets 100% of demonstrated financial need.',
    tags: ['usa', 'mit', 'need-blind', 'stem', 'fully-funded'],
  },

  // ─── UK — MERIT + PARTIAL ──────────────────────────────────
  {
    id: 'commonwealth_scholarship',
    name: 'Commonwealth Scholarship (UK)',
    provider: 'Commonwealth Scholarship Commission',
    country: 'UK',
    region: 'uk',
    eligibility: {
      min_performance: '75_85',
      target_fields: ['general', 'stem', 'research'],
      country_restriction: 'Commonwealth countries',
      requires_entrance_exam: false,
      requires_research: true,
      requires_community_service: true,
    },
    coverage: 'full',
    coverage_details: 'Full tuition, living allowance, airfare, thesis grant for master\'s/PhD in UK',
    amount_usd_thousands: 50,
    amount_inr_lakhs: 42,
    difficulty: 8,
    acceptance_rate_percent: 8,
    deadline_month: 'December',
    required_documents: ['SOP', '2 LORs', 'Academic transcripts', 'Development impact statement', 'CV'],
    description: 'Fully funded scholarships for students from Commonwealth countries to study in the UK.',
    tags: ['uk', 'commonwealth', 'fully-funded', 'development', 'masters-phd'],
  },
  {
    id: 'chevening_scholarship',
    name: 'Chevening Scholarship',
    provider: 'UK Foreign, Commonwealth & Development Office',
    country: 'UK',
    region: 'uk',
    eligibility: {
      min_performance: '75_85',
      target_fields: ['general', 'law', 'research'],
      requires_entrance_exam: false,
      requires_research: false,
      requires_community_service: true,
    },
    coverage: 'full',
    coverage_details: 'Full tuition, monthly stipend, travel costs, arrival allowance for 1-year UK master\'s',
    amount_usd_thousands: 45,
    amount_inr_lakhs: 38,
    difficulty: 8,
    acceptance_rate_percent: 6,
    deadline_month: 'November',
    required_documents: ['SOP', '2 LORs', 'Work experience proof (2 years)', 'Leadership evidence', 'UK university offers'],
    description: 'UK\'s flagship scholarship for future leaders with 2+ years of work experience.',
    tags: ['uk', 'chevening', 'leadership', 'fully-funded', 'masters'],
  },
  {
    id: 'gates_cambridge',
    name: 'Gates Cambridge Scholarship',
    provider: 'Bill & Melinda Gates Foundation',
    country: 'UK',
    region: 'uk',
    eligibility: {
      min_performance: '95_plus',
      target_fields: ['general', 'stem', 'research'],
      requires_entrance_exam: false,
      requires_research: true,
      requires_community_service: true,
    },
    coverage: 'full',
    coverage_details: 'Full cost of studying at Cambridge: tuition, maintenance, travel, research costs',
    amount_usd_thousands: 60,
    amount_inr_lakhs: 50,
    difficulty: 10,
    acceptance_rate_percent: 3,
    deadline_month: 'October',
    required_documents: ['SOP', '3 LORs', 'Research proposal', 'CV', 'Cambridge application'],
    description: 'One of the most prestigious scholarships in the world for postgraduate study at Cambridge.',
    tags: ['uk', 'cambridge', 'elite', 'research', 'fully-funded'],
  },

  // ─── EUROPE — LOW COST + PARTIAL ───────────────────────────
  {
    id: 'daad_scholarship',
    name: 'DAAD Scholarship (Germany)',
    provider: 'German Academic Exchange Service',
    country: 'Germany',
    region: 'europe',
    eligibility: {
      min_performance: '75_85',
      target_fields: ['stem', 'research', 'general'],
      requires_entrance_exam: false,
      requires_research: false,
      requires_community_service: false,
    },
    coverage: 'partial_75',
    coverage_details: '€934/month living allowance + health insurance + travel for master\'s/PhD programs',
    amount_usd_thousands: 25,
    amount_inr_lakhs: 21,
    difficulty: 6,
    acceptance_rate_percent: 20,
    deadline_month: 'October',
    required_documents: ['SOP', '2 LORs', 'CV', 'German university admission', 'Language proficiency (German/English)'],
    description: 'Germany\'s premier exchange service funding. Most German public universities have no tuition.',
    tags: ['europe', 'germany', 'daad', 'low-tuition', 'masters-phd'],
  },
  {
    id: 'erasmus_mundus',
    name: 'Erasmus Mundus Joint Master Degree (EMJMD)',
    provider: 'European Commission',
    country: 'Multiple EU countries',
    region: 'europe',
    eligibility: {
      min_performance: '75_85',
      target_fields: ['general', 'stem', 'arts', 'research'],
      requires_entrance_exam: false,
      requires_research: false,
      requires_community_service: false,
    },
    coverage: 'full',
    coverage_details: 'Full tuition (up to €9,000/yr), €1,400/month living, travel, insurance for 2-year joint master\'s',
    amount_usd_thousands: 50,
    amount_inr_lakhs: 42,
    difficulty: 7,
    acceptance_rate_percent: 12,
    deadline_month: 'January',
    required_documents: ['SOP', '2 LORs', 'CV', 'Language certificate', 'Transcripts', 'Research interest statement'],
    description: 'Study in 2-3 European countries in a fully-funded, internationally recognized joint master\'s.',
    tags: ['europe', 'eu', 'erasmus', 'multi-country', 'fully-funded'],
  },

  // ─── GLOBAL / MULTI-COUNTRY ────────────────────────────────
  {
    id: 'aga_khan_foundation',
    name: 'Aga Khan Foundation International Scholarship',
    provider: 'Aga Khan Development Network',
    country: 'Global',
    region: 'global',
    eligibility: {
      min_performance: '75_85',
      max_family_income_lpa: 10,
      target_fields: ['general'],
      requires_entrance_exam: false,
      requires_research: false,
      requires_community_service: true,
    },
    coverage: 'partial_50',
    coverage_details: '50% grant + 50% loan model for postgraduate studies at top global universities',
    amount_usd_thousands: 30,
    amount_inr_lakhs: 25,
    difficulty: 7,
    acceptance_rate_percent: 10,
    deadline_month: 'March',
    required_documents: ['SOP', '2 LORs', 'Financial need documentation', 'Community service proof', 'University admission'],
    description: 'For students from developing countries who have no other means of financing their studies.',
    tags: ['global', 'need-based', 'postgraduate', 'development'],
  },
  {
    id: 'rhodes_scholarship',
    name: 'Rhodes Scholarship (Oxford)',
    provider: 'Rhodes Trust',
    country: 'UK',
    region: 'uk',
    eligibility: {
      min_performance: '95_plus',
      target_fields: ['general', 'research'],
      requires_entrance_exam: false,
      requires_research: true,
      requires_community_service: true,
    },
    coverage: 'full',
    coverage_details: 'Full tuition, living stipend, airfare, health insurance for postgraduate study at Oxford',
    amount_usd_thousands: 70,
    amount_inr_lakhs: 58,
    difficulty: 10,
    acceptance_rate_percent: 1,
    deadline_month: 'August',
    required_documents: ['SOP', '5 LORs', 'Leadership portfolio', 'Athletic/creative portfolio', 'Oxford application'],
    description: 'The oldest and most prestigious international scholarship. For exceptional all-rounders.',
    tags: ['uk', 'oxford', 'elite', 'all-rounder', 'fully-funded'],
  },

  // ─── SPORTS-SPECIFIC ───────────────────────────────────────
  {
    id: 'sai_tops_scheme',
    name: 'SAI TOPS (Target Olympic Podium Scheme)',
    provider: 'Sports Authority of India',
    country: 'India',
    region: 'india',
    eligibility: {
      min_performance: 'below_60',
      target_fields: ['sports'],
      requires_entrance_exam: false,
      requires_research: false,
      requires_community_service: false,
    },
    coverage: 'full',
    coverage_details: 'Full training, coaching, equipment, travel, nutrition, and competition funding for elite athletes',
    amount_inr_lakhs: 15,
    difficulty: 9,
    acceptance_rate_percent: 2,
    deadline_month: 'Year-round',
    required_documents: ['National-level competition results', 'Sports federation recommendation', 'Medical fitness'],
    description: 'India\'s premier sports funding scheme for athletes with Olympic medal potential.',
    tags: ['india', 'sports', 'olympic', 'elite-athlete', 'government'],
  },
  {
    id: 'sports_quota_admission',
    name: 'Sports Quota Admission (Indian Universities)',
    provider: 'Various Indian Universities',
    country: 'India',
    region: 'india',
    eligibility: {
      min_performance: 'below_60',
      target_fields: ['sports', 'general'],
      requires_entrance_exam: false,
      requires_research: false,
      requires_community_service: false,
    },
    coverage: 'partial_50',
    coverage_details: 'Reserved seats with fee concession (50-100%) at DU, JNU, BHU, etc. for state/national athletes',
    amount_inr_lakhs: 3,
    difficulty: 5,
    acceptance_rate_percent: 20,
    deadline_month: 'June',
    required_documents: ['Sports certificates (state/national)', 'Fitness certificate', 'University application'],
    description: 'Guaranteed admission in top universities through sports quota with significant fee reduction.',
    tags: ['india', 'sports', 'quota', 'university', 'fee-waiver'],
  },

  // ─── ARTS / CREATIVE ───────────────────────────────────────
  {
    id: 'jn_tata_endowment',
    name: 'JN Tata Endowment Loan Scholarship',
    provider: 'JN Tata Endowment Trust',
    country: 'Global',
    region: 'global',
    eligibility: {
      min_performance: '75_85',
      target_fields: ['general', 'arts', 'stem', 'research'],
      country_restriction: 'India',
      requires_entrance_exam: false,
      requires_research: false,
      requires_community_service: false,
    },
    coverage: 'partial_75',
    coverage_details: 'Interest-free loan + gift grant (₹1-10L) for Indian students studying abroad',
    amount_inr_lakhs: 10,
    difficulty: 6,
    acceptance_rate_percent: 15,
    deadline_month: 'March',
    required_documents: ['Admission letter (foreign university)', 'SOP', 'Transcripts', 'LORs', 'Financial need statement'],
    description: 'One of India\'s oldest and most respected scholarship trusts for students going abroad.',
    tags: ['global', 'india-origin', 'loan-scholarship', 'study-abroad', 'tata'],
  },
  {
    id: 'inlaks_scholarship',
    name: 'Inlaks Shivdasani Foundation Scholarship',
    provider: 'Inlaks Foundation',
    country: 'USA/UK/Europe',
    region: 'global',
    eligibility: {
      min_performance: '85_95',
      target_fields: ['general', 'arts', 'stem', 'research'],
      country_restriction: 'India',
      requires_entrance_exam: false,
      requires_research: false,
      requires_community_service: false,
    },
    coverage: 'full',
    coverage_details: 'Up to $100,000 covering tuition, living expenses for study at top US/UK/EU universities',
    amount_usd_thousands: 100,
    amount_inr_lakhs: 83,
    difficulty: 8,
    acceptance_rate_percent: 5,
    deadline_month: 'April',
    required_documents: ['SOP', '3 LORs', 'Academic transcripts', 'Admission offers from top universities', 'CV'],
    description: 'Prestigious Indian scholarship for exceptional students admitted to world-class institutions.',
    tags: ['global', 'india-origin', 'fully-funded', 'elite', 'postgraduate'],
  },
];

// ─── DOMAIN TO SCHOLARSHIP TARGET MAPPING ────────────────────
export const DOMAIN_TO_SCHOLARSHIP_TARGET: Record<string, string[]> = {
  tech_ai: ['stem', 'general', 'research'],
  medical: ['medical', 'general', 'research'],
  sports: ['sports', 'general'],
  arts_creative: ['arts', 'general'],
  commerce_business: ['commerce', 'general'],
  government_law: ['law', 'general'],
  emerging_hybrid: ['stem', 'general', 'research'],
};
