// Career expansion generator - outputs TypeScript career entries
// Run: node scripts/generate-careers.cjs > lib/careers-expansion-data.ts
const fs = require('fs');

// Compact career definitions: [id, name, aliases[], streams[], type, domain, cat, minM, minMS, timeline, global, exam|null, roi, stress, desc, reality, semTags[], negKw[], skills[3][name,skills[],resource,months], insts[][name,tier,city,state,fees,cutoff,placement,type], salary[entry,mid,senior]]
const C = [
// ── HEALTHCARE SPECIALIZATIONS ──
["radiologist","Radiologist",["radiology","x-ray","mri","ct scan","imaging","diagnostic radiology"],["PCB"],"B","healthcare","Research",88,78,9,false,"NEET-UG",7,8,
"Interpret medical images (X-ray, MRI, CT) to diagnose diseases. High-demand specialty with excellent work-life balance.",
"Radiology is 5.5yr MBBS + 3yr MD Radiology. Seats are extremely limited — only ~800 MD Radiology seats in India. Private college fees can exceed ₹1Cr.",
["radiology","imaging","diagnostic","mri","ct"],["photographer","photography"],
[["NEET Preparation",["Physics","Chemistry","Biology","MCQ Strategy"],"Allen/Aakash + PW",18],["Clinical Foundation",["Anatomy","Physiology","Pathology","Radiology basics"],"Robbins + Radiopaedia",24],["Specialization",["MRI Physics","CT Protocols","Interventional Radiology"],"Defined Radiology + AIIMS material",36]],
[["AIIMS New Delhi",1,"New Delhi","Delhi",1628,"NEET Top 50","₹15L","government"],["CMC Vellore",1,"Vellore","Tamil Nadu",70000,"NEET Top 500","₹12L","private"],["KEM Hospital",1,"Mumbai","Maharashtra",25000,"NEET Top 800","₹12L","government"]],
["₹8-15 LPA","₹25-60 LPA","₹80-300 LPA"]],

["dentist","Dentist (BDS)",["dental","bds","dental surgeon","orthodontist","dentistry","teeth"],["PCB"],"B","healthcare","Research",75,60,5,false,"NEET-UG",6,5,
"Diagnose and treat dental conditions. Growing demand in cosmetic dentistry and orthodontics.",
"BDS has poor ROI compared to MBBS. Most dentists earn ₹3-5L initially. The market is oversaturated in urban India with 300+ dental colleges.",
["dental","dentistry","oral","teeth"],["data","dental insurance"],
[["NEET Preparation",["Physics","Chemistry","Biology"],"Allen/Aakash",18],["Dental Sciences",["Oral Anatomy","Prosthodontics","Orthodontics"],"BDS curriculum",48],["Practice Setup",["Clinic Management","Patient Relations","Equipment"],"Dental associations",12]],
[["Maulana Azad Dental College",1,"Delhi","Delhi",15000,"NEET Top 5000","₹6L","government"],["Manipal MCODS",1,"Manipal","Karnataka",800000,"NEET 550+","₹8L","private"],["Government Dental College",1,"Mumbai","Maharashtra",20000,"NEET Top 8000","₹5L","government"]],
["₹3-8 LPA","₹10-25 LPA","₹30-80 LPA"]],

["physiotherapist","Physiotherapist",["physio","physical therapy","rehabilitation","bpt","sports physio"],["PCB"],"A","healthcare","Research",65,50,4,false,null,6,4,
"Help patients recover mobility through exercises and manual therapy. Growing demand in sports and geriatric care.",
"BPT is undervalued in India — starting salaries are ₹2-4L. The real money is in sports physiotherapy or opening your own clinic, both of which take 5-10 years.",
["physiotherapy","rehabilitation","physical therapy","mobility"],["physics","physician"],
[["Anatomy & Biomechanics",["Anatomy","Kinesiology","Biomechanics","Exercise Science"],"BPT Curriculum",24],["Clinical Skills",["Manual Therapy","Electrotherapy","Sports Rehab"],"Clinical rotations",18],["Specialization",["Sports Physio","Neuro Rehab","Pediatric Physio"],"IASM/Sports authority courses",12]],
[["CMC Vellore",1,"Vellore","Tamil Nadu",60000,"NEET/Entrance","₹5L","private"],["AIIMS Delhi",1,"Delhi","Delhi",1628,"NEET-based","₹6L","government"],["SVNIRTAR Cuttack",1,"Cuttack","Odisha",15000,"Entrance exam","₹4L","government"]],
["₹2-5 LPA","₹6-15 LPA","₹20-50 LPA"]],

["pharmacist","Pharmacist",["pharmacy","b.pharm","d.pharm","pharmaceutical","drug","pharma","medicines"],["PCB","PCM"],"A","healthcare","Research",60,45,4,false,null,6,4,
"Develop, test, and dispense medications. Pharma industry is India's 3rd largest globally.",
"B.Pharm graduates rarely do actual pharmacy — most go into pharma sales or manufacturing. Clinical pharmacy roles are few. D.Pharm has very limited career growth.",
["pharmacy","pharmaceutical","drug","medicine formulation"],["physician","physics"],
[["Pharmaceutical Sciences",["Organic Chemistry","Pharmacology","Pharmaceutics"],"B.Pharm curriculum",24],["Industry Skills",["Drug Formulation","Quality Control","Regulatory Affairs"],"NIPER resources",18],["Research/Business",["Clinical Trials","Pharmacovigilance","Marketing"],"Industry internships",12]],
[["NIPER Mohali",1,"Mohali","Punjab",50000,"GPAT Top 500","₹8L","government"],["ICT Mumbai",1,"Mumbai","Maharashtra",80000,"MHT-CET/JEE","₹7L","government"],["JSS Mysuru",1,"Mysuru","Karnataka",150000,"Entrance exam","₹5L","private"]],
["₹3-6 LPA","₹8-20 LPA","₹25-60 LPA"]],

["veterinarian","Veterinarian",["vet","veterinary","animal doctor","bvsc","animal science"],["PCB"],"B","healthcare","Research",65,50,5,false,"NEET-UG (Veterinary)",5,6,
"Diagnose and treat animals. India has only ~100k vets for 500M+ livestock — massive shortage.",
"BVSc is 5.5 years but starting pay is ₹3-5L. Government vet jobs pay well but are rural postings. Urban pet practice is growing but saturated in metros.",
["veterinary","animal","livestock","pet"],["venture","veteran"],
[["NEET/Entrance",["Biology","Chemistry","Animal Science"],"NEET prep + ICAR AIEEA",18],["Veterinary Sciences",["Animal Anatomy","Pathology","Surgery","Medicine"],"BVSc curriculum",48],["Specialization",["Dairy Science","Wildlife","Pet Practice"],"MVSc/Internships",24]],
[["IVRI Bareilly",1,"Bareilly","Uttar Pradesh",20000,"ICAR AIEEA Top 200","₹6L","government"],["GADVASU Ludhiana",1,"Ludhiana","Punjab",30000,"NEET/State entrance","₹5L","government"],["TANUVAS Chennai",1,"Chennai","Tamil Nadu",25000,"NEET-based","₹5L","government"]],
["₹3-6 LPA","₹8-18 LPA","₹20-50 LPA"]],

// ── ENGINEERING SPECIALIZATIONS ──
["robotics_engineer","Robotics Engineer",["robotics","robots","automation","mechatronics","ros","robotic systems"],["PCM"],"A","technology","Technical",75,60,4,true,"JEE Main / JEE Advanced",8,7,
"Design and build robots and automated systems. Booming with Industry 4.0 and warehouse automation.",
"India's robotics industry is nascent — most high-paying jobs are abroad or at MNCs. Pure robotics roles in India are rare; most work in automation/IoT.",
["robotics","automation","robot","mechatronics","actuator"],["rocket","rocketry"],
[["Engineering Core",["Mechanics","Electronics","Control Systems","Embedded C"],"B.Tech Mechatronics/ECE",24],["Robotics Stack",["ROS","Computer Vision","SLAM","Motion Planning"],"MIT OCW + Coursera Robotics",12],["Industry Prep",["Industrial Automation","PLC/SCADA","Collaborative Robots"],"Company internships",6]],
[["IIT Madras",1,"Chennai","Tamil Nadu",220000,"JEE Advanced Top 500","₹20L","government"],["BITS Pilani",1,"Pilani","Rajasthan",550000,"BITSAT 340+","₹14L","deemed"],["MIT Manipal",2,"Manipal","Karnataka",400000,"MET exam","₹8L","private"]],
["₹6-12 LPA","₹15-40 LPA","₹50-120 LPA"]],

["biomedical_engineer","Biomedical Engineer",["biomedical","medical devices","biotech engineering","prosthetics","medical instruments"],["PCM","PCB"],"A","healthcare","Technical",72,58,4,true,null,7,5,
"Design medical devices, prosthetics, and diagnostic equipment. Bridge between engineering and medicine.",
"Biomedical engineering sounds exciting but job market in India is very small. Most graduates end up in IT or generic manufacturing. Best opportunities are abroad or in pharma MNCs.",
["biomedical","medical device","prosthetic","implant","bioinstrumentation"],["biology","biotechnology research"],
[["Engineering Base",["Circuits","Signal Processing","Biomechanics","Materials"],"B.Tech Biomedical curriculum",24],["Medical Technology",["Medical Imaging","Biomaterials","Tissue Engineering"],"NPTEL + IEEE courses",12],["Industry Skills",["FDA/CDSCO Regulations","Quality Systems","Clinical Trials"],"Company internships",6]],
[["IIT Hyderabad",1,"Hyderabad","Telangana",220000,"JEE Advanced","₹15L","government"],["VIT Vellore",2,"Vellore","Tamil Nadu",200000,"VITEEE","₹6L","private"],["CMC Vellore BME",1,"Vellore","Tamil Nadu",80000,"Entrance exam","₹8L","private"]],
["₹4-8 LPA","₹10-25 LPA","₹30-80 LPA"]],

["environmental_engineer","Environmental Engineer",["environment","pollution control","waste management","sustainability","green engineering","climate"],["PCM"],"A","environment","Technical",68,55,4,true,null,6,5,
"Solve environmental problems — water treatment, air quality, waste management, sustainability consulting.",
"Very few pure environmental engineering jobs in India. Most work is in EIA consulting or government pollution boards. NGOs pay poorly. Best ROI is abroad.",
["environment","pollution","waste","water treatment","sustainability","climate"],["interior","fashion"],
[["Engineering Core",["Environmental Chemistry","Fluid Mechanics","Thermodynamics"],"B.Tech Environmental curriculum",24],["Specialization",["Water Treatment","Air Quality Modeling","EIA","Waste Management"],"NPTEL + EPA resources",12],["Professional",["Environmental Law","GIS","Remote Sensing","Sustainability Reporting"],"MOOC + Internships",6]],
[["IIT Bombay (ESED)",1,"Mumbai","Maharashtra",220000,"JEE Advanced Top 2000","₹16L","government"],["IIT Madras",1,"Chennai","Tamil Nadu",220000,"JEE Advanced","₹15L","government"],["NIT Trichy",1,"Tiruchirappalli","Tamil Nadu",180000,"JEE Main Top 10000","₹8L","government"]],
["₹4-8 LPA","₹10-25 LPA","₹25-60 LPA"]],

["food_technologist","Food Technologist",["food technology","food science","food processing","fssai","food safety","dairy technology"],["PCM","PCB"],"A","science","Technical",60,45,4,false,null,5,3,
"Develop and improve food products, ensure safety standards, manage food processing operations.",
"Food tech is underrated but stable. FSSAI and food safety compliance roles are growing. Best placements come from NIFTEM and CFTRI. Dairy tech has excellent govt job prospects.",
["food","dairy","nutrition","processing","fssai","quality control"],["fashion","footwear"],
[["Food Science Base",["Food Chemistry","Microbiology","Nutrition","Processing"],"B.Tech Food Tech curriculum",24],["Industry Skills",["HACCP","ISO 22000","Sensory Evaluation","Packaging"],"FSSAI + CFTRI courses",12],["Specialization",["Dairy Tech","Bakery","Beverage","Quality Assurance"],"Industry internships",6]],
[["NIFTEM Kundli",1,"Sonipat","Haryana",100000,"JEE Main/Special exam","₹8L","government"],["CFTRI Mysore",1,"Mysuru","Karnataka",30000,"GATE/Entrance","₹6L","government"],["ICT Mumbai",1,"Mumbai","Maharashtra",80000,"MHT-CET/JEE","₹7L","government"]],
["₹3-6 LPA","₹8-18 LPA","₹20-40 LPA"]],

["mining_engineer","Mining Engineer",["mining","mines","mineral extraction","coal","iron ore"],["PCM"],"A","engineering","Technical",62,50,4,false,"JEE Main / GATE",6,8,
"Plan and manage mining operations for minerals, coal, and metals. Critical for India's resource economy.",
"Mining engineering has excellent govt job prospects (Coal India, NMDC, ONGC) but postings are always in remote areas. Safety risks are real. Urban jobs are rare.",
["mining","mineral","excavation","coal","ore","quarry"],["data mining","bitcoin mining"],
[["Engineering Core",["Rock Mechanics","Mine Planning","Surveying","Geology"],"B.Tech Mining curriculum",24],["Specialization",["Blasting Technology","Mine Safety","Environmental Mining"],"ISM Dhanbad resources",12],["Professional",["DGMS Certifications","Mine Management","GIS/Remote Sensing"],"Industry training",6]],
[["IIT ISM Dhanbad",1,"Dhanbad","Jharkhand",220000,"JEE Advanced/Main","₹12L","government"],["NIT Rourkela",1,"Rourkela","Odisha",180000,"JEE Main","₹8L","government"],["VNIT Nagpur",1,"Nagpur","Maharashtra",180000,"JEE Main","₹7L","government"]],
["₹5-10 LPA","₹12-30 LPA","₹35-80 LPA"]],

// ── GOVERNMENT SERVICES ──
["ips_officer","IPS Officer",["ips","police","superintendent","commissioner","law enforcement","indian police service"],["Any"],"B","government","Government",75,60,5,false,"UPSC Civil Services",8,10,
"Lead police forces, maintain law and order, investigate crimes. One of India's most powerful positions.",
"IPS selection rate is <0.05%. You compete with lakhs of graduates. Age limit 32 (General). Most selected candidates have 3-5 attempts. Physical fitness standards are strict.",
["police","ips","law enforcement","crime","security","investigation"],["software","coding"],
[["UPSC Foundation",["Polity","History","Geography","Ethics","Essay"],"Laxmikanth + Spectrum",12],["Optional + Mains",["Optional Subject","Answer Writing","Current Affairs"],"Vision IAS / Forum IAS",12],["Physical + Interview",["Physical Fitness","Personality Test","Medical Standards"],"LBSNAA training reference",6]],
[["LBSNAA Mussoorie",1,"Mussoorie","Uttarakhand",0,"UPSC CSE Final Rank Top 200","₹12L","government"],["SVPNPA Hyderabad",1,"Hyderabad","Telangana",0,"IPS Allocation","₹12L","government"]],
["₹8-12 LPA","₹15-25 LPA","₹25-40 LPA (+ perks)"]],

["ifs_officer","IFS Officer (Foreign Service)",["ifs","diplomat","embassy","foreign service","diplomacy","ambassador","indian foreign service"],["Any"],"B","government","Government",78,65,5,true,"UPSC Civil Services",7,7,
"Represent India abroad, negotiate treaties, protect Indian citizens overseas. Elite diplomatic career.",
"Even harder than IAS — only ~30 IFS officers selected per year. You'll spend most of your career abroad, which sounds glamorous but means constant relocation and family disruption.",
["diplomat","diplomacy","foreign affairs","embassy","consulate","international relations"],["software","forex"],
[["UPSC Foundation",["International Relations","Polity","History","Geography"],"Laxmikanth + Pavneet Singh IR",12],["Mains + Optional",["Answer Writing","Essay","Optional Subject"],"Vajiram / Forum IAS",12],["Interview Prep",["Current Affairs","Personality","Communication"],"Mock interviews",6]],
[["LBSNAA Mussoorie",1,"Mussoorie","Uttarakhand",0,"UPSC CSE + IFS preference","₹12L","government"],["FSI (Foreign Service Institute)",1,"Delhi","Delhi",0,"IFS Allocation","₹12L","government"]],
["₹8-12 LPA","₹15-25 LPA","₹25-40 LPA (+ allowances)"]],

["rbi_grade_b","RBI Grade B Officer",["rbi","reserve bank","banking regulator","monetary policy","central banking"],["Any"],"B","finance","Government",78,65,4,false,"RBI Grade B Exam",7,6,
"Work at India's central bank — monetary policy, banking regulation, forex management, financial stability.",
"RBI Grade B is one of the best govt exams for Commerce/Economics graduates. ~300 vacancies/year. Excellent pay (₹12L+ starting) and prestige. But the exam is very competitive.",
["rbi","central bank","monetary","banking regulation","forex reserve"],["retail banking","bank clerk"],
[["Economics Foundation",["Macro/Micro Economics","Monetary Policy","Indian Economy"],"Ramesh Singh + EPW",8],["Exam Preparation",["Quantitative Aptitude","Reasoning","English","Finance"],"Oliveboard + Unacademy",10],["Interview",["Economic Analysis","Current Affairs","Banking Knowledge"],"Mock interviews",3]],
[["RBI Central Office",1,"Mumbai","Maharashtra",0,"RBI Grade B Exam","₹12L","government"],["RBI Regional Office",1,"Various","Various",0,"RBI Grade B Exam","₹12L","government"]],
["₹12-15 LPA","₹18-30 LPA","₹35-55 LPA"]],

// ── LAW SPECIALIZATIONS ──
["corporate_lawyer","Corporate Lawyer",["corporate law","m&a lawyer","mergers acquisitions","commercial law","business lawyer","transactional lawyer"],["Any"],"B","law","Other",80,65,5,true,"CLAT / LSAT",8,8,
"Handle mergers, acquisitions, contracts, and corporate compliance. Highest-paying legal specialization.",
"Corporate law at a top firm (AZB, Khaitan, Cyril) pays ₹15-20L starting — but you'll work 80-100 hour weeks. Burnout is the #1 exit reason. Only NLU grads get these firms easily.",
["corporate law","m&a","merger","acquisition","contract","compliance"],["criminal","family law"],
[["Law Foundation",["Constitutional Law","Contract Law","Corporate Law","Legal Research"],"CLAT prep + NLU curriculum",36],["Corporate Specialization",["Securities Law","M&A","Due Diligence","Drafting"],"NLU electives + Internships",24],["Career Ops",["Moot Court","Internships at top firms","Legal Writing"],"Bar Council + firm internships",12]],
[["NLSIU Bangalore",1,"Bangalore","Karnataka",250000,"CLAT Top 50","₹20L","private"],["NALSAR Hyderabad",1,"Hyderabad","Telangana",200000,"CLAT Top 100","₹18L","private"],["NLU Delhi",1,"Delhi","Delhi",200000,"AILET Top 80","₹18L","government"]],
["₹10-20 LPA","₹30-80 LPA","₹1-5 Cr PA"]],

["cyber_lawyer","Cyber Lawyer",["cyber law","it law","data privacy","information technology law","digital law","internet law","gdpr"],["Any"],"B","law","Other",70,55,5,true,"CLAT / LSAT",7,5,
"Handle cybercrime cases, data privacy compliance, IT Act disputes. Fastest-growing legal specialization.",
"Very new field in India — demand is growing fast but structured career paths barely exist. Most 'cyber lawyers' are general lawyers who handle some IT Act cases.",
["cyber law","data privacy","cybercrime","it act","digital","gdpr","data protection"],["cybersecurity engineer","hacking"],
[["Law Foundation",["Constitutional Law","Criminal Law","IT Act 2000"],"LLB/BA-LLB curriculum",36],["Cyber Specialization",["Data Privacy Laws","Cybercrime Investigation","Digital Evidence"],"NLSIU/NALSAR courses + Cert programs",12],["Technical Skills",["Basic Networking","Digital Forensics Concepts","Blockchain Law"],"Online courses + Conferences",6]],
[["NLSIU Bangalore",1,"Bangalore","Karnataka",250000,"CLAT Top 50","₹15L","private"],["NLU Delhi",1,"Delhi","Delhi",200000,"AILET","₹14L","government"],["Symbiosis Law School",2,"Pune","Maharashtra",350000,"SLAT exam","₹8L","private"]],
["₹5-10 LPA","₹15-35 LPA","₹40-100 LPA"]],

// ── BUSINESS/MANAGEMENT ──
["management_consultant","Management Consultant",["consulting","mckinsey","bcg","bain","strategy consultant","business consultant","mbb"],["Any"],"A","business","Other",82,70,6,true,null,9,9,
"Advise companies on strategy, operations, and organizational transformation. Elite business career.",
"MBB (McKinsey/BCG/Bain) recruit almost exclusively from IIMs and top global MBA programs. Without a top MBA, you'll likely end up at mid-tier firms with very different pay and prestige.",
["consulting","strategy","management","business advisory","mbb","mckinsey","bcg"],["counseling","therapy"],
[["Academic Foundation",["Economics","Statistics","Business Strategy","Case Studies"],"UG degree + MBA prep",24],["MBA",["Strategy","Operations","Finance","Leadership"],"IIM/ISB/Top global MBA",24],["Consulting Skills",["Frameworks","Slide Writing","Client Management","Data Analysis"],"Case in Point + Victor Cheng",6]],
[["IIM Ahmedabad",1,"Ahmedabad","Gujarat",2500000,"CAT 99.9+","₹35L","government"],["IIM Bangalore",1,"Bangalore","Karnataka",2500000,"CAT 99.5+","₹32L","government"],["ISB Hyderabad",1,"Hyderabad","Telangana",4200000,"GMAT 720+","₹35L","private"]],
["₹15-25 LPA","₹40-80 LPA","₹1-4 Cr PA"]],

["product_manager","Product Manager",["pm","product management","product owner","apm","product strategy"],["Any"],"A","technology","Technical",75,60,4,true,null,9,7,
"Define what gets built, why, and for whom. Bridge between business, design, and engineering.",
"PM is the most overhyped career in tech. Everyone wants to be a PM but there are 10x fewer PM roles than SWE roles. Most 'PM' titles at startups are glorified project managers.",
["product management","product strategy","roadmap","user research","agile"],["project manager","production manager"],
[["Technical Foundation",["Basic Coding","System Design","Data Analysis","SQL"],"CS degree or bootcamp",12],["PM Skills",["User Research","PRDs","Wireframing","A/B Testing","Metrics"],"Lenny's Newsletter + Reforge",6],["Career Ops",["Portfolio Projects","APM Programs","Mock PMs"],"Exponent + Product School",6]],
[["IIT Bombay",1,"Mumbai","Maharashtra",220000,"JEE Advanced","₹20L","government"],["BITS Pilani",1,"Pilani","Rajasthan",550000,"BITSAT","₹14L","deemed"],["IIM Ahmedabad (MBA)",1,"Ahmedabad","Gujarat",2500000,"CAT 99.9+","₹35L","government"]],
["₹12-25 LPA","₹30-60 LPA","₹70-200 LPA"]],

// ── MEDIA/COMMUNICATION ──
["news_anchor","News Anchor / TV Journalist",["news anchor","tv journalist","news reader","broadcast journalist","television reporter","newsroom"],[" Any"],"C","media","Creative",65,50,3,false,null,5,8,
"Present news on television, conduct interviews, and report on current events. High visibility career.",
"Only a handful of anchors become famous and well-paid. Most TV journalists earn ₹3-8L and work grueling hours. Print is dying. Digital media pays even less but has more freedom.",
["news","anchor","broadcast","television","journalist","newsroom"],["youtube","blogger"],
[["Journalism Foundation",["News Writing","Reporting","Media Ethics","Current Affairs"],"IIMC/Symbiosis/AJK MCRC",24],["Broadcast Skills",["Camera Presence","Voice Modulation","Teleprompting","Live Reporting"],"Internships at news channels",12],["Digital Transition",["Social Media","Video Editing","Podcasting"],"Online platforms",6]],
[["IIMC Delhi",1,"Delhi","Delhi",35000,"Entrance exam","₹5L","government"],["AJK MCRC Jamia",1,"Delhi","Delhi",25000,"Entrance exam","₹4L","government"],["Symbiosis (SIMC)",2,"Pune","Maharashtra",400000,"SET exam","₹6L","private"]],
["₹3-8 LPA","₹10-25 LPA","₹30-100 LPA"]],

["advertising_professional","Advertising Professional",["advertising","ad agency","copywriter","art director","creative director","advertising campaign","ad copy"],[" Any"],"C","media","Creative",60,45,3,true,null,7,7,
"Create advertising campaigns — copywriting, art direction, strategy. Drive brand storytelling.",
"Ad agencies are fun but underpay compared to tech. Junior copywriters earn ₹3-5L. The hours are brutal during campaign seasons. Most people burn out by 30 and move to brand-side roles.",
["advertising","ad agency","campaign","copywriting","creative","brand"],["data","software ad"],
[["Creative Foundation",["Copywriting","Visual Design","Brand Strategy","Consumer Psychology"],"Mass Comm degree",24],["Agency Skills",["Campaign Planning","Media Buying","Digital Marketing","Social Media"],"Internships at agencies",12],["Portfolio",["Award Entries","Client Presentations","Reel Building"],"Industry events",6]],
[["MICA Ahmedabad",1,"Ahmedabad","Gujarat",2200000,"MICAT exam","₹18L","private"],["IIMC Delhi",1,"Delhi","Delhi",35000,"Entrance exam","₹5L","government"],["Xavier's Mumbai (BMM)",1,"Mumbai","Maharashtra",80000,"XAT/Merit","₹6L","private"]],
["₹3-6 LPA","₹10-25 LPA","₹30-80 LPA"]],

["technical_writer","Technical Writer",["technical writing","documentation","api docs","user manual","content developer","doc writer"],["Any"],"A","technology","Technical",60,45,3,true,null,6,3,
"Write documentation, API guides, user manuals for software products. Hidden gem career in tech.",
"Technical writing is one of the most underrated careers in tech. It pays nearly as much as dev roles (₹8-20L) with much less stress. But most people don't know it exists as a career.",
["technical writing","documentation","api","manual","docs"],["creative writing","fiction"],
[["Writing Foundation",["Grammar","Technical Communication","Information Architecture"],"Online courses + practice",6],["Tech Skills",["Markdown","Git","API Understanding","DITA/DocBook"],"Google Technical Writing course",4],["Tools & Practice",["Swagger/OpenAPI","Confluence","ReadTheDocs","Style Guides"],"Open source documentation",6]],
[["IIT Bombay (any degree)",1,"Mumbai","Maharashtra",220000,"JEE Advanced","₹20L","government"],["BITS Pilani",1,"Pilani","Rajasthan",550000,"BITSAT","₹14L","deemed"]],
["₹4-8 LPA","₹10-22 LPA","₹25-50 LPA"]],

["pr_specialist","Public Relations Specialist",["pr","public relations","communications","press","media relations","corporate communications"],[" Any"],"A","media","Creative",60,45,3,true,null,6,6,
"Manage public image for organizations and individuals. Crisis communication, media relations, reputation management.",
"PR is relationship-driven — who you know matters more than what you know. Agency PR is hectic with multiple clients. In-house PR is calmer but slower to grow. Digital PR is the future.",
["public relations","pr","communications","media relations","press","reputation"],["programming","development"],
[["Communication Foundation",["Writing","Media Relations","Crisis Communication","Public Speaking"],"Mass Comm degree",24],["PR Skills",["Press Releases","Event Management","Social Media","Influencer Relations"],"PR agency internships",12],["Digital PR",["SEO PR","Content Marketing","Analytics","Online Reputation"],"Online courses",6]],
[["IIMC Delhi",1,"Delhi","Delhi",35000,"Entrance exam","₹5L","government"],["Symbiosis SIMC",2,"Pune","Maharashtra",400000,"SET","₹6L","private"],["MICA Ahmedabad",1,"Ahmedabad","Gujarat",2200000,"MICAT","₹15L","private"]],
["₹3-6 LPA","₹8-20 LPA","₹25-60 LPA"]],

["social_media_manager","Social Media Manager",["social media","instagram manager","content creator","digital marketing","community manager","influencer marketing"],["Any"],"A","media","Creative",50,35,2,true,null,7,5,
"Manage brand presence on social platforms. Content strategy, community building, paid campaigns.",
"Low barrier to entry means oversaturation. Most social media managers earn ₹3-6L. The ones who earn well (₹15L+) are data-driven strategists at large brands, not just 'posting content'.",
["social media","instagram","linkedin","content","community","digital marketing"],["software","engineering"],
[["Digital Marketing Foundation",["Content Strategy","SEO/SEM","Analytics","Copywriting"],"Google Digital Garage + HubSpot",6],["Platform Mastery",["Instagram","LinkedIn","YouTube","Paid Ads","Reels"],"Practice + brand internships",6],["Analytics & Strategy",["Google Analytics","Meta Business Suite","A/B Testing","ROI Tracking"],"Coursera/Udemy courses",4]],
[["MICA Ahmedabad",1,"Ahmedabad","Gujarat",2200000,"MICAT","₹15L","private"],["IIMC Delhi",1,"Delhi","Delhi",35000,"Entrance","₹5L","government"]],
["₹3-6 LPA","₹8-18 LPA","₹20-40 LPA"]],

// ── EDUCATION/RESEARCH ──
["professor","University Professor",["professor","academic","researcher","faculty","lecturer","phd","academia","teaching"],[" Any"],"A","education","Research",80,65,8,true,null,5,5,
"Teach at universities, conduct research, publish papers. Intellectual freedom but slow career growth.",
"PhD takes 4-6 years. Then postdoc 2-3 years. Then assistant professor at 30+. India has very few tenure-track positions. NET/SET is mandatory. Pay at state universities is poor (₹3-5L for adhoc).",
["professor","academic","research","university","teaching","faculty","phd"],["coaching","tutoring"],
[["Academic Foundation",["Deep subject mastery","Research Methodology","Academic Writing"],"UG + PG in chosen field",36],["PhD & Research",["Thesis","Publications","Conferences","Grant Writing"],"PhD program",48],["Teaching",["Pedagogy","Curriculum Design","Student Mentoring"],"UGC NET + teaching experience",12]],
[["JNU Delhi",1,"Delhi","Delhi",20000,"Entrance + PhD admission","₹8L","government"],["IISc Bangalore",1,"Bangalore","Karnataka",15000,"GATE/NET + Interview","₹10L","government"],["Delhi University",1,"Delhi","Delhi",25000,"UGC NET + Interview","₹8L","government"]],
["₹4-8 LPA","₹10-20 LPA","₹18-35 LPA"]],

["school_teacher","School Teacher",["teacher","school teacher","teaching","educator","tutor","cbse teacher","icse teacher"],[" Any"],"A","education","Other",55,40,4,false,"CTET / State TET",4,5,
"Teach students at school level. Foundational role in shaping society. Stable but underpaid career.",
"Government school teachers have excellent job security and decent pay (₹4-8L). Private school teachers are exploited — ₹15-25K/month is common. Coaching teachers can earn ₹20L+ but it's hustle.",
["teacher","teaching","school","education","cbse","icse","pedagogy"],["tech","software"],
[["Subject Mastery",["Deep knowledge in chosen subject","Curriculum understanding"],"B.Ed + subject degree",24],["Teaching Skills",["Pedagogy","Classroom Management","Assessment Design"],"B.Ed program",24],["Certification",["CTET","State TET","NET (for higher secondary)"],"Exam preparation",6]],
[["NCERT/RIE",1,"Various","Various",15000,"B.Ed entrance","₹6L","government"],["Jamia Millia B.Ed",1,"Delhi","Delhi",20000,"Entrance exam","₹6L","government"],["Azim Premji University",1,"Bangalore","Karnataka",200000,"Entrance + Interview","₹5L","private"]],
["₹2-5 LPA","₹5-12 LPA","₹12-25 LPA"]],

["edtech_professional","EdTech Professional",["edtech","education technology","online education","elearning","byju","unacademy","learning platform"],["Any"],"A","technology","Technical",65,50,3,true,null,7,6,
"Build and manage online education platforms, create digital learning experiences, develop ed-tech products.",
"EdTech bubble burst in 2023-24 (Byju's crash). The sector is recovering but hiring is cautious. Content creation roles are low-paying. Product/engineering roles pay well. Be cautious.",
["edtech","education technology","online learning","elearning","lms"],["electrical","embedded"],
[["Tech/Education Foundation",["Web Development","Instructional Design","Learning Science"],"CS/Education degree",24],["EdTech Skills",["LMS Platforms","Video Production","Gamification","Analytics"],"Industry experience",12],["Growth",["Product Management","AI in Education","Adaptive Learning"],"Conferences + courses",6]],
[["IIT Bombay",1,"Mumbai","Maharashtra",220000,"JEE Advanced","₹18L","government"],["IIM Bangalore",1,"Bangalore","Karnataka",2500000,"CAT 99.5+","₹30L","government"]],
["₹5-12 LPA","₹15-30 LPA","₹35-80 LPA"]],

// ── EMERGING TECH ──
["prompt_engineer","AI Prompt Engineer",["prompt engineer","prompt engineering","llm","ai prompt","generative ai","chatgpt","gemini engineer"],["Any"],"A","technology","Technical",70,55,2,true,null,8,4,
"Design and optimize prompts for large language models. Newest career in AI — emerged 2023.",
"Prompt engineering as a standalone career is already dying. It's becoming a skill, not a job. Companies want AI engineers who can also prompt, not prompt-only specialists. Learn to code.",
["prompt","llm","generative ai","chatgpt","gemini","ai","large language model"],["civil","mechanical"],
[["AI Foundation",["Machine Learning basics","NLP","Transformer Architecture"],"Fast.ai + Andrej Karpathy",6],["Prompt Engineering",["Few-shot","Chain-of-thought","RAG","Fine-tuning concepts"],"OpenAI docs + DeepLearning.ai",3],["Applied AI",["API Integration","LangChain","Vector DBs","Evaluation"],"Projects + GitHub portfolio",6]],
[["IIT Bombay",1,"Mumbai","Maharashtra",220000,"JEE Advanced","₹20L","government"],["IIIT Hyderabad",1,"Hyderabad","Telangana",300000,"UGEE","₹16L","deemed"]],
["₹8-15 LPA","₹18-40 LPA","₹50-120 LPA"]],

["cybersecurity_analyst","Cybersecurity Analyst",["cybersecurity","security analyst","ethical hacker","infosec","penetration testing","soc analyst","information security"],["PCM"],"A","technology","Technical",70,55,4,true,null,8,7,
"Protect organizations from cyber threats. Penetration testing, incident response, security architecture.",
"Cybersecurity has a massive talent shortage globally (3.5M unfilled jobs). India is a major hub. But entry-level roles require strong networking/OS fundamentals. Certifications (CEH, OSCP) matter more than degrees.",
["cybersecurity","security","hacking","penetration","firewall","infosec","soc"],["cyber law","insurance"],
[["CS Foundation",["Networking","Operating Systems","Linux","Scripting"],"B.Tech CS + TryHackMe",18],["Security Core",["Ethical Hacking","OWASP","Cryptography","Incident Response"],"CEH + PortSwigger labs",12],["Advanced",["Cloud Security","OSCP","Threat Hunting","Malware Analysis"],"HackTheBox + SANS courses",12]],
[["IIT Kanpur (C3i)",1,"Kanpur","Uttar Pradesh",220000,"JEE Advanced","₹18L","government"],["IIIT Delhi",1,"Delhi","Delhi",350000,"JAC entrance","₹14L","government"],["Amrita University",2,"Coimbatore","Tamil Nadu",250000,"AEEE","₹8L","private"]],
["₹5-10 LPA","₹12-30 LPA","₹35-80 LPA"]],

["cloud_architect","Cloud Architect",["cloud","aws","azure","gcp","cloud computing","devops","cloud engineer","infrastructure"],["PCM"],"A","technology","Technical",72,58,4,true,null,9,6,
"Design and manage cloud infrastructure. AWS, Azure, GCP. One of the highest-paying tech specializations.",
"Cloud roles pay extremely well (₹20-60L mid-career) but require deep infrastructure knowledge. Certifications (AWS SA, Azure Solutions) are almost mandatory. Competition is intense.",
["cloud","aws","azure","gcp","infrastructure","devops","kubernetes"],["weather","meteorology"],
[["CS Foundation",["Linux","Networking","Programming","Databases"],"B.Tech CS curriculum",24],["Cloud Core",["AWS/Azure/GCP","Containers","Kubernetes","Terraform","CI/CD"],"Cloud provider training + A Cloud Guru",12],["Architecture",["Microservices","Serverless","Security","Cost Optimization"],"AWS SA cert + real projects",6]],
[["IIT Bombay",1,"Mumbai","Maharashtra",220000,"JEE Advanced","₹22L","government"],["NIT Trichy",1,"Tiruchirappalli","Tamil Nadu",180000,"JEE Main","₹12L","government"],["BITS Pilani",1,"Pilani","Rajasthan",550000,"BITSAT","₹14L","deemed"]],
["₹8-15 LPA","₹20-50 LPA","₹60-150 LPA"]],

["blockchain_developer","Blockchain Developer",["blockchain","web3","smart contracts","solidity","ethereum","crypto developer","defi"],["PCM"],"A","technology","Technical",72,58,3,true,null,8,6,
"Build decentralized applications, smart contracts, and blockchain protocols. Web3 specialization.",
"Blockchain hype has cooled significantly since 2022. Real jobs exist but are fewer than the hype suggests. Most 'blockchain companies' in India are small and unstable. Learn core CS first.",
["blockchain","smart contract","web3","defi","ethereum","solidity","decentralized"],["chain supply","logistics chain"],
[["CS Foundation",["DSA","Cryptography","Distributed Systems","Networking"],"B.Tech CS",24],["Blockchain Core",["Solidity","EVM","Smart Contract Security","DeFi Protocols"],"CryptoZombies + Alchemy University",6],["Full Stack Web3",["React/Next.js","Ethers.js","IPFS","Layer 2s"],"Buildspace + Hackathons",6]],
[["IIT Kharagpur",1,"Kharagpur","West Bengal",220000,"JEE Advanced","₹18L","government"],["IIIT Hyderabad",1,"Hyderabad","Telangana",300000,"UGEE","₹16L","deemed"]],
["₹8-18 LPA","₹20-50 LPA","₹50-200 LPA"]],

["xr_designer","XR Designer (AR/VR)",["vr","ar","mixed reality","virtual reality","augmented reality","metaverse","xr","spatial computing"],["PCM","Arts"],"A","technology","Creative",65,50,4,true,null,7,5,
"Design immersive experiences in AR/VR/MR. Apple Vision Pro and Meta Quest are driving demand.",
"XR is still niche in India — very few full-time XR roles. Most work is project-based or at global companies remotely. The tech is maturing but mass adoption hasn't happened yet.",
["virtual reality","augmented reality","mixed reality","xr","spatial","immersive","metaverse"],["interior design","graphic design"],
[["3D Foundation",["3D Modeling","Unity/Unreal","C#/C++","Spatial Design"],"Game dev or design degree",24],["XR Development",["ARKit/ARCore","WebXR","Shader Programming","UX for VR"],"Unity XR courses + Meta docs",12],["Portfolio",["XR Projects","Hackathons","App Store Releases"],"Personal projects",6]],
[["IIT Bombay (IDC)",1,"Mumbai","Maharashtra",220000,"CEED + JEE","₹18L","government"],["NID Ahmedabad",1,"Ahmedabad","Gujarat",250000,"NID DAT","₹12L","government"]],
["₹5-12 LPA","₹15-35 LPA","₹40-100 LPA"]],

["iot_engineer","IoT Engineer",["iot","internet of things","embedded iot","smart devices","connected devices","sensor networks"],["PCM"],"A","technology","Technical",68,55,4,true,null,7,5,
"Build connected device ecosystems — smart homes, industrial IoT, wearables, sensor networks.",
"IoT in India is mostly in industrial applications (manufacturing, agriculture). Consumer IoT startups have high failure rates. Core embedded + cloud skills are needed — it's not just 'connecting things'.",
["iot","internet of things","sensor","connected","smart device","embedded","wearable"],["software only","web development"],
[["Electronics Foundation",["Circuits","Microcontrollers","Sensors","Embedded C"],"B.Tech ECE/EEE",24],["IoT Stack",["MQTT","LoRa","Edge Computing","Cloud Integration","ESP32/Arduino"],"Coursera IoT + Hackster.io",12],["Data & Security",["Time Series Data","IoT Security","ML on Edge","Dashboard Design"],"Projects + Internships",6]],
[["IIT Madras",1,"Chennai","Tamil Nadu",220000,"JEE Advanced","₹18L","government"],["BITS Pilani",1,"Pilani","Rajasthan",550000,"BITSAT","₹14L","deemed"],["MIT Manipal",2,"Manipal","Karnataka",400000,"MET","₹8L","private"]],
["₹5-10 LPA","₹12-28 LPA","₹30-70 LPA"]],

// ── NICHE/UNIQUE ──
["forensic_accountant","Forensic Accountant",["forensic accounting","fraud investigator","financial crime","fraud examiner","cfe","anti-money laundering"],["Commerce"],"B","finance","Financial",75,60,5,false,"CA/CPA + CFE",7,6,
"Investigate financial fraud, embezzlement, money laundering. Combines accounting with detective work.",
"Forensic accounting is niche but growing fast (corporate fraud, cyber fraud, GST fraud). Big 4 firms hire forensic teams. But you need CA + additional certifications (CFE). Pure investigators are rare in India.",
["forensic accounting","fraud","financial crime","investigation","audit","aml"],["forensic science","crime scene"],
[["Accounting Foundation",["Financial Accounting","Auditing","Taxation","Company Law"],"CA Foundation + Inter",36],["Forensic Skills",["Fraud Detection","Digital Forensics","AML/KYC","Data Analytics"],"CFE + ACFE courses",12],["Legal Knowledge",["PMLA","IT Act","Companies Act","Expert Witness Testimony"],"Law courses + Internships",6]],
[["ICAI (CA Program)",1,"Various","Various",50000,"CA Foundation Exam","₹8L","government"],["IIM Bangalore (Forensic Audit PG)",1,"Bangalore","Karnataka",2500000,"CAT","₹30L","government"]],
["₹5-10 LPA","₹15-35 LPA","₹40-100 LPA"]],

["meteorologist","Meteorologist",["meteorology","weather","climate science","weather forecasting","atmospheric science","imd"],["PCM"],"A","science","Research",72,58,5,false,null,5,4,
"Study and predict weather patterns, climate change, atmospheric phenomena. Critical for agriculture and disaster management.",
"Very few meteorologist positions in India — mostly at IMD, ISRO, or universities. Private sector weather companies are emerging but small. PhD is almost mandatory for research roles.",
["meteorology","weather","climate","atmosphere","forecasting","imd"],["meter","measurement"],
[["Physics/Math Foundation",["Atmospheric Physics","Fluid Dynamics","Statistics","Programming"],"B.Sc Physics/Atmospheric Science",24],["Meteorology Specialization",["Numerical Weather Prediction","Remote Sensing","Climate Modeling"],"M.Sc Atmospheric Science",24],["Research/Career",["FORTRAN/Python","GIS","Satellite Data","Publication"],"IMD/IITM internship",12]],
[["IIT Delhi (CAS)",1,"Delhi","Delhi",220000,"JEE Advanced/GATE","₹12L","government"],["IITM Pune",1,"Pune","Maharashtra",20000,"GATE/NET","₹8L","government"],["Andhra University",1,"Visakhapatnam","Andhra Pradesh",30000,"Entrance","₹4L","government"]],
["₹4-8 LPA","₹10-20 LPA","₹18-35 LPA"]],

["archaeologist","Archaeologist",["archaeology","excavation","heritage","ancient history","antiquities","historical sites"],["Arts"],"A","humanities","Research",65,50,6,false,null,3,4,
"Excavate and study ancient civilizations, artifacts, and historical sites. Preserve cultural heritage.",
"Archaeology in India has extremely limited career options — ASI (Archaeological Survey of India) or universities. Pay is low (₹3-6L government). Field work is physically demanding. Passion-driven career.",
["archaeology","excavation","ancient","heritage","artifact","civilization","history"],["architecture","software architect"],
[["History Foundation",["Ancient History","Art History","Anthropology","Epigraphy"],"BA History/Archaeology",24],["Fieldwork Skills",["Excavation Techniques","Dating Methods","GIS","Documentation"],"MA Archaeology + Field schools",24],["Research",["Publication","Museum Curation","Heritage Conservation","Grants"],"PhD + ASI internship",24]],
[["Deccan College Pune",1,"Pune","Maharashtra",15000,"Entrance exam","₹4L","government"],["JNU (SLS)",1,"Delhi","Delhi",20000,"JNUEE","₹5L","government"],["BHU Archaeology",1,"Varanasi","Uttar Pradesh",10000,"BHU UET","₹4L","government"]],
["₹3-6 LPA","₹8-15 LPA","₹15-25 LPA"]],

["oceanographer","Oceanographer",["ocean","marine science","oceanography","sea research","coastal","ocean exploration"],["PCM","PCB"],"A","science","Research",72,58,6,true,null,4,4,
"Study oceans — currents, marine ecosystems, underwater geology, climate impact. Critical for coastal India.",
"Very niche field — maybe 200-300 active oceanographers in India. NIO Goa, NIOT Chennai, INCOIS Hyderabad are the main employers. PhD mandatory for research. Field work involves long ship voyages.",
["ocean","marine","oceanography","coastal","underwater","sea"],["marine engineer","shipping"],
[["Science Foundation",["Physics","Chemistry","Biology","Math","Programming"],"B.Sc relevant field",24],["Oceanography",["Physical Oceanography","Chemical Oceanography","Biological Oceanography"],"M.Sc/M.Tech Oceanography",24],["Research",["Data Analysis","Ship-based Research","Remote Sensing","Climate Models"],"PhD + NIO/NIOT",36]],
[["NIO Goa",1,"Goa","Goa",20000,"GATE/NET","₹8L","government"],["NIOT Chennai",1,"Chennai","Tamil Nadu",25000,"GATE","₹8L","government"],["Cochin University (CUSAT)",1,"Kochi","Kerala",30000,"CUSAT CAT","₹5L","government"]],
["₹4-8 LPA","₹10-20 LPA","₹18-35 LPA"]],

["museum_curator","Museum Curator",["curator","museum","art gallery","exhibition","heritage conservation","museology"],["Arts"],"A","humanities","Creative",60,45,5,false,null,3,3,
"Manage museum collections, plan exhibitions, preserve artifacts. Bridge between art, history, and public education.",
"Museum jobs in India are scarce and poorly paid. National Museum Institute is the only premier institution. Most curators at government museums earn ₹4-6L. Private galleries in Delhi/Mumbai pay better.",
["museum","curator","exhibition","gallery","heritage","conservation","artifact"],["music","musician"],
[["Arts/History Foundation",["Art History","Cultural Studies","Anthropology","Conservation"],"BA History/Fine Arts",24],["Museology",["Collection Management","Exhibition Design","Conservation Science"],"MA Museology/NMI",24],["Professional",["Grant Writing","Public Programming","Digital Museums","Cataloging"],"Museum internships",12]],
[["National Museum Institute",1,"Delhi","Delhi",15000,"Entrance exam","₹5L","government"],["MS University Baroda",1,"Vadodara","Gujarat",10000,"Entrance","₹3L","government"],["JNU (Arts & Aesthetics)",1,"Delhi","Delhi",20000,"JNUEE","₹5L","government"]],
["₹3-5 LPA","₹6-12 LPA","₹15-25 LPA"]],

// ── DEFENCE ──
["defence_officer","Defence Officer (Army/Navy/Air Force)",["army","navy","air force","defence","military","nda","cds","indian army","officer"],["Any"],"B","government","Government",70,55,5,false,"NDA / CDS / AFCAT",7,10,
"Lead military operations, defend the nation. Prestigious career with unmatched discipline and adventure.",
"NDA entry is at 16.5-19.5 years after 12th. CDS after graduation. Physical fitness is non-negotiable. You'll be posted in remote areas, conflict zones. Family life is disrupted. But the perks (housing, pension, canteen) are excellent.",
["army","navy","air force","military","defence","officer","nda","cds"],["software","civil"],
[["Exam Preparation",["Mathematics","General Knowledge","English","Reasoning"],"NDA/CDS coaching",12],["Training",["Physical Fitness","Military Tactics","Leadership","Weapons"],"IMA/OTA/AFA/INA",12],["Service",["Specialized Training","Staff College","Higher Command"],"Military institutions",24]],
[["IMA Dehradun",1,"Dehradun","Uttarakhand",0,"NDA/CDS/Direct Entry","₹10L","government"],["NDA Khadakwasla",1,"Pune","Maharashtra",0,"NDA Exam + SSB","₹8L","government"],["AFA Dundigal",1,"Hyderabad","Telangana",0,"NDA/CDS/AFCAT + SSB","₹10L","government"]],
["₹8-12 LPA","₹15-25 LPA","₹25-40 LPA (+ perks)"]],

["merchant_navy","Merchant Navy Officer",["merchant navy","shipping","marine engineer","deck officer","seafarer","nautical"],["PCM"],"B","maritime","Technical",65,50,4,true,"IMU-CET",8,8,
"Navigate ships, manage cargo operations, maintain marine engines. High-paying career on the seas.",
"Merchant navy pays extremely well (₹15-30L tax-free for engineers) but you'll spend 6-9 months at sea with no family. Mental isolation is real. Women face additional challenges. Career span is 15-20 years.",
["merchant navy","ship","maritime","seafarer","navigation","marine"],["navy military","coastguard"],
[["Foundation",["Mathematics","Physics","Navigation","Marine Engineering"],"IMU-CET prep",12],["Cadetship",["Ship Operations","Engine Room","Safety","Cargo"],"Maritime academy",36],["Certification",["COC Exams","STCW","Specialized Certifications"],"DG Shipping",12]],
[["IMU Mumbai",1,"Mumbai","Maharashtra",300000,"IMU-CET","₹15L","government"],["MERI Mumbai",1,"Mumbai","Maharashtra",400000,"IMU-CET","₹15L","private"],["TMI Pune",1,"Pune","Maharashtra",500000,"IMU-CET","₹12L","private"]],
["₹8-15 LPA","₹20-40 LPA (tax-free)","₹50-100 LPA (Captain)"]],

["isro_scientist","Space Scientist (ISRO)",["isro","space","satellite","rocket scientist","space research","chandrayaan","mangalyaan"],["PCM"],"B","science","Research",82,70,6,false,"ICRB Exam / GATE",6,6,
"Design satellites, rockets, and space missions. India's space program is world-class on a budget.",
"ISRO is incredibly hard to get into — they hire ~200 scientists/year from lakhs of applicants. Pay is government scale (₹8-15L) which is low vs private sector. But the work is literally rocket science.",
["space","isro","satellite","rocket","aerospace","chandrayaan","mars"],["astrology","astronomy hobby"],
[["Engineering/Science",["Aerospace","Mechanical","Electronics","CS","Physics"],"B.Tech/M.Sc from IIT/NIT",24],["GATE/ICRB",["GATE Score","ISRO-specific Preparation","Technical Interview"],"GATE coaching + self-study",12],["Research",["Propulsion","Avionics","Remote Sensing","Mission Design"],"ISRO centres",36]],
[["IIT Madras (Aerospace)",1,"Chennai","Tamil Nadu",220000,"JEE Advanced Top 1000","₹18L","government"],["IIT Bombay (Aerospace)",1,"Mumbai","Maharashtra",220000,"JEE Advanced Top 800","₹20L","government"],["IISc Bangalore",1,"Bangalore","Karnataka",15000,"GATE Top 100","₹10L","government"]],
["₹8-12 LPA","₹15-25 LPA","₹25-40 LPA"]],

// ── TRADES/VOCATIONAL ──
["chef","Professional Chef",["chef","cooking","culinary","hotel management","baking","pastry","food","restaurant"],["Any"],"C","hospitality","Creative",50,35,3,true,null,6,8,
"Create culinary experiences in restaurants, hotels, catering. India's food industry is ₹5L Cr+.",
"Hotel management is oversaturated — IHM graduates earn ₹2-4L starting. Fine dining chef roles pay better but demand 14-16 hour shifts. Own restaurant is the goal but 60% fail in year 1.",
["chef","culinary","cooking","restaurant","hotel","kitchen","food"],["chemistry","chemical"],
[["Culinary Foundation",["Cooking Techniques","Food Safety","Nutrition","Baking"],"IHM/Culinary school",24],["Specialization",["Cuisine Mastery","Pastry Arts","Kitchen Management","Menu Design"],"Hotel internships",12],["Business",["Restaurant Management","Cost Control","Marketing","F&B Operations"],"Industry experience",12]],
[["IHM Mumbai",1,"Mumbai","Maharashtra",100000,"JEE (Hotel Management)","₹5L","government"],["IHM Delhi",1,"Delhi","Delhi",100000,"JEE (HM)","₹5L","government"],["Welcomgroup Manipal",1,"Manipal","Karnataka",400000,"Entrance","₹6L","private"]],
["₹2-5 LPA","₹6-15 LPA","₹20-50 LPA (Executive Chef)"]],

["electrician","Master Electrician",["electrician","electrical technician","wiring","iti electrical","power distribution"],["Any"],"C","trades","Other",40,30,2,false,"ITI Certificate",5,6,
"Install, maintain, and repair electrical systems. Essential trade with growing demand in India.",
"ITI electricians can earn ₹3-5L working for contractors. Skilled electricians running own business earn ₹8-15L. Solar installation is a booming sub-specialization. Govt jobs (BSNL, railways) pay ₹4-6L.",
["electrician","wiring","electrical","power","circuit","installation"],["electronics engineer","electrical engineer degree"],
[["ITI Foundation",["Basic Electrical","Circuit Theory","Safety","Wiring"],"ITI Electrician course",24],["Advanced Skills",["Industrial Wiring","PLC Basics","Solar Installation","EV Charging"],"Apprenticeship + certifications",12],["Business",["Contracting","Estimation","Team Management","Licensing"],"Field experience",12]],
[["Govt ITI Delhi",1,"Delhi","Delhi",5000,"10th pass + Merit","₹3L","government"],["Govt ITI Mumbai",1,"Mumbai","Maharashtra",5000,"10th pass","₹3L","government"]],
["₹2-4 LPA","₹5-10 LPA","₹12-25 LPA (Contractor)"]],

["plumber","Master Plumber",["plumber","plumbing","pipefitting","sanitary","water systems"],["Any"],"C","trades","Other",35,25,2,false,"ITI Certificate",5,5,
"Install and maintain water supply, drainage, and gas piping systems. Massive shortage in India.",
"India has a severe plumber shortage — organized plumbing services like UrbanClap have created new earning opportunities. Skilled plumbers earn ₹5-10L. No social stigma should stop you — it's honest, well-paying work.",
["plumber","plumbing","pipe","sanitary","drainage","water system"],["software","coding"],
[["ITI Foundation",["Pipe Fitting","Sanitary Systems","Blueprint Reading","Safety"],"ITI Plumber course",24],["Advanced",["CPVC/PPR","Bathroom Design","Water Purification","Gas Fitting"],"Apprenticeship",12],["Business",["Contracting","Customer Service","Estimation","Team Building"],"Field experience",12]],
[["Govt ITI",1,"Various","Various",5000,"10th pass","₹2L","government"]],
["₹2-4 LPA","₹5-10 LPA","₹12-20 LPA (Contractor)"]],

["welder","Certified Welder",["welder","welding","fabrication","tig","mig","arc welding"],["Any"],"C","trades","Other",40,30,2,false,"ITI Certificate / ASNT",6,7,
"Join metals through welding — essential for construction, shipbuilding, oil & gas, aerospace.",
"Skilled welders, especially underwater/pipeline welders, can earn ₹15-30L. Regular welders earn ₹3-6L. International certifications (AWS, ASNT) dramatically increase earning. Gulf/abroad jobs pay 3x.",
["welding","welder","fabrication","metal","joining","tig","mig"],["web developer","software"],
[["ITI Foundation",["Arc Welding","Gas Welding","Safety","Blueprint Reading"],"ITI Welder course",24],["Advanced",["TIG","MIG","Pipe Welding","Underwater Welding"],"Specialized training",12],["Certification",["AWS CWI","ASNT","6G Certification","NDT"],"Certification bodies",6]],
[["Govt ITI",1,"Various","Various",5000,"10th pass","₹2L","government"],["CWS Vishakhapatnam",1,"Visakhapatnam","Andhra Pradesh",15000,"10th pass + test","₹4L","government"]],
["₹2-5 LPA","₹6-15 LPA","₹20-40 LPA (Specialist)"]],

// ── SPORTS ──
["sports_physiologist","Sports Scientist / Physiologist",["sports science","exercise science","sports medicine","fitness","kinesiology","sports physiology"],["PCB","PCM"],"A","sports","Research",65,50,4,true,null,5,4,
"Optimize athlete performance through science — biomechanics, nutrition, recovery, testing.",
"Sports science in India is underdeveloped. BCCI, ISL, PKL teams hire sports scientists but positions are few. Most end up as gym trainers earning ₹3-5L. International qualifications (ACSM, NSCA) help.",
["sports science","exercise","fitness","biomechanics","kinesiology","athletic"],["esports","gaming"],
[["Science Foundation",["Anatomy","Physiology","Biomechanics","Nutrition"],"B.Sc Sports Science",24],["Applied Sports Science",["Performance Testing","Injury Prevention","Rehabilitation","GPS Tracking"],"M.Sc Sports Science",24],["Certification",["CSCS (NSCA)","ACSM","Strength & Conditioning"],"Certification courses",6]],
[["LNIPE Gwalior",1,"Gwalior","Madhya Pradesh",25000,"Entrance exam","₹4L","government"],["SAI NSNIS Patiala",1,"Patiala","Punjab",15000,"Selection","₹5L","government"],["Symbiosis Sports Science",2,"Pune","Maharashtra",300000,"Entrance","₹5L","private"]],
["₹3-6 LPA","₹8-18 LPA","₹20-40 LPA"]],

["sports_journalist","Sports Journalist",["sports journalist","cricket commentator","sports reporter","sports writing","espn","sports media"],["Any"],"C","media","Creative",55,40,3,true,null,5,6,
"Cover sports events, write match reports, analyze games, do commentary. Dream career for sports fans.",
"Sports journalism in India = cricket journalism for most outlets. Other sports get minimal coverage and pay. Starting pay is ₹2-4L at most outlets. Only top commentators/analysts earn well.",
["sports","cricket","football","journalist","commentary","reporting","match"],["financial reporting","news anchor"],
[["Journalism Foundation",["Sports Writing","Reporting","Media Ethics","Statistics"],"Mass Comm degree",24],["Sports Expertise",["Deep sport knowledge","Data Analysis","Video Analysis","Social Media"],"Sports blogs + internships",12],["Career Building",["Portfolio","Networking","Personal Brand","Podcasting"],"Industry events",6]],
[["IIMC Delhi",1,"Delhi","Delhi",35000,"Entrance exam","₹5L","government"],["Symbiosis (SIMC)",2,"Pune","Maharashtra",400000,"SET","₹6L","private"]],
["₹2-5 LPA","₹6-15 LPA","₹20-50 LPA"]],

["esports_professional","Esports Professional",["esports","gaming","professional gamer","game streamer","esports manager","competitive gaming"],["Any"],"C","entertainment","Creative",40,30,2,true,null,6,7,
"Compete in professional gaming tournaments or manage esports teams/events. India's gaming market is ₹25,000 Cr.",
"Only the top 0.01% of gamers earn enough to sustain. Most 'pro gamers' in India earn ₹0-2L/year from tournaments. Streaming income requires 100K+ followers. Esports management/content is more viable long-term.",
["esports","gaming","competitive gaming","streaming","tournament","pubg","valorant"],["sports physical","athlete"],
[["Gaming Skills",["Game Mastery","Reaction Time","Strategy","Team Coordination"],"Daily practice (8-12hrs)",12],["Content/Streaming",["Video Editing","Streaming Setup","Commentary","Community Building"],"YouTube/Twitch practice",6],["Business Side",["Tournament Organization","Team Management","Sponsorship","Marketing"],"Esports orgs internship",6]],
[["No formal institution — community-driven",2,"Various","Various",0,"Tournament qualification","₹2-5L","private"]],
["₹0-3 LPA","₹5-20 LPA","₹30-200 LPA (top tier)"]],

// ── CREATIVE ──
["music_producer","Music Producer / Sound Engineer",["music producer","sound engineer","audio engineer","mixing","mastering","music production","recording"],["Any"],"C","entertainment","Creative",45,30,3,true,null,6,5,
"Produce music tracks, mix and master audio, run recording studios. Bollywood and indie music scenes are thriving.",
"Music production requires expensive equipment (₹5-10L setup). Income is project-based and inconsistent. Bollywood pays well but is nepotistic. Indie scene is growing but monetization is tough.",
["music","producer","audio","sound","recording","mixing","mastering"],["software producer","film producer"],
[["Music Theory",["Harmony","Rhythm","Arrangement","Ear Training"],"Self-study + online courses",12],["Production Skills",["DAW (Ableton/FL Studio)","Mixing","Mastering","Sound Design"],"Online courses + practice",12],["Industry",["Networking","Portfolio","Live Sound","Studio Business"],"Internships at studios",6]],
[["Film and TV Institute (FTII)",1,"Pune","Maharashtra",50000,"Entrance exam","₹5L","government"],["SAE Institute",2,"Mumbai","Maharashtra",600000,"Portfolio review","₹6L","private"]],
["₹2-5 LPA","₹6-20 LPA","₹25-100 LPA"]],

["interior_designer","Interior Designer",["interior design","home design","space planning","interior decorator","residential design","commercial interiors"],["Any","Arts"],"C","design","Creative",55,40,4,true,null,6,5,
"Design functional and aesthetic indoor spaces — homes, offices, restaurants, retail stores.",
"Interior design in India is unregulated — anyone can call themselves a designer. But formal training (NID, CEPT, JJ School) gives you an edge. Starting pay is poor (₹3-5L). Own practice is where the money is.",
["interior","space design","home","decor","furniture","residential","commercial"],["software","web design"],
[["Design Foundation",["Space Planning","Color Theory","Materials","Drawing"],"B.Des Interior Design",24],["Technical Skills",["AutoCAD","3ds Max","SketchUp","Vastu","Building Codes"],"Design software courses",12],["Business",["Client Management","Vendor Relations","Project Management","Portfolio"],"Internships + own projects",12]],
[["NID Ahmedabad",1,"Ahmedabad","Gujarat",250000,"NID DAT","₹8L","government"],["CEPT Ahmedabad",1,"Ahmedabad","Gujarat",300000,"Entrance exam","₹7L","private"],["JJ School of Art",1,"Mumbai","Maharashtra",15000,"Drawing test","₹5L","government"]],
["₹3-6 LPA","₹8-20 LPA","₹25-80 LPA (Own firm)"]],

["tattoo_artist","Tattoo Artist",["tattoo","tattoo artist","body art","ink","tattooing"],["Any"],"C","art","Creative",35,25,2,false,null,6,4,
"Create permanent body art. India's tattoo industry is ₹2000 Cr and growing 25% annually.",
"No formal degree needed but apprenticeship under a good artist is crucial (1-2 years). Starting income is ₹2-4L. Established artists in metros earn ₹15-30L. Hygiene certification is important. It's a craft, not just art.",
["tattoo","body art","ink","piercing","art","illustration"],["software","technology"],
[["Art Foundation",["Drawing","Illustration","Anatomy","Color Theory"],"Art classes + self-study",12],["Apprenticeship",["Machine Operation","Hygiene","Skin Knowledge","Style Development"],"Under established artist",18],["Business",["Portfolio","Social Media","Studio Setup","Client Management"],"Personal branding",6]],
[["No formal institution — apprenticeship-based",2,"Various","Various",50000,"Portfolio + Apprenticeship","₹5L","private"]],
["₹2-5 LPA","₹8-20 LPA","₹25-60 LPA (Own studio)"]],

["event_manager","Event Manager",["event management","event planner","wedding planner","corporate events","exhibitions","festivals"],["Any"],"C","hospitality","Creative",55,40,3,true,null,6,8,
"Plan and execute events — weddings, corporate conferences, exhibitions, concerts. India's wedding industry is ₹4L Cr.",
"Event management is glamorous on the outside but grueling — 18-hour days during events, seasonal income, high stress. Starting pay is ₹2-4L. Top event companies (Wizcraft, E-Factor) pay ₹8-15L mid-level.",
["event","wedding","conference","exhibition","planning","festival"],["software event","data event"],
[["Foundation",["Event Planning","Budgeting","Vendor Management","Logistics"],"Event Management diploma",12],["Specialization",["Wedding Planning","Corporate Events","Exhibition Design","Digital Events"],"Internships",12],["Business",["Client Relations","Marketing","Team Management","Risk Management"],"Industry experience",12]],
[["NIEM Mumbai",2,"Mumbai","Maharashtra",200000,"Entrance","₹4L","private"],["EMDI Delhi",2,"Delhi","Delhi",250000,"Entrance","₹4L","private"],["Symbiosis",2,"Pune","Maharashtra",400000,"SET","₹6L","private"]],
["₹2-5 LPA","₹6-15 LPA","₹20-50 LPA (Own company)"]],
];

// Factory function
function expand(c) {
  return {
    id: c[0], name: c[1], aliases: c[2], streams: c[3], careerType: c[4], domain: c[5],
    category: c[6], minMarks: c[7], minMarksStretch: c[8], timeline: c[9], globalScope: c[10],
    examRequired: c[11], roiScore: c[12], stressScore: c[13], description: c[14], realityNote: c[15],
    semantic_tags: c[16], keywords_negative: c[17],
    domains: c[18].map(d => ({ name: d[0], skills: d[1], topResource: d[2], timeMonths: d[3] })),
    topInstitutions: c[19].map(i => ({ name: i[0], tier: i[1], city: i[2], state: i[3], fees_per_year: i[4], cutoff_description: i[5], placement_median: i[6], type: i[7] })),
    salaryRange: { entry: c[20][0], mid: c[20][1], senior: c[20][2] }
  };
}

// Generate output
const careers = C.map(expand);
let out = `// AUTO-GENERATED — do not edit manually\n// Run: node scripts/generate-careers.cjs > lib/careers-expansion-data.ts\n\nimport type { CareerProfile } from './career-database';\n\nexport const CAREERS_EXPANSION: Record<string, CareerProfile> = {\n`;
for (const c of careers) {
  out += `  ${c.id}: ${JSON.stringify(c, null, 4).split('\n').map((l,i) => i===0 ? l : '  '+l).join('\n')},\n`;
}
out += `};\n`;
fs.writeFileSync(require('path').join(__dirname, '..', 'lib', 'careers-expansion-data.ts'), out);
console.log(`Generated ${careers.length} careers to lib/careers-expansion-data.ts`);
